repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format --check
        language: system
        types: [python]

      - id: ruff-lint
        name: ruff lint
        entry: ruff check
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["atlas"]

      - id: prettier
        name: prettier
        entry: prettier --check
        language: system
        types_or: [javascript, jsx, ts, tsx, css, json, yaml, markdown]

      - id: eslint
        name: eslint
        entry: eslint --max-warnings 0
        language: system
        types_or: [javascript, jsx, ts, tsx]
