#!/usr/bin/env sh
set -eu

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=scripts/release/scout-homebrew-resources.sh
. "$script_dir/scout-homebrew-resources.sh"

die() {
  echo "scout-homebrew: $*" >&2
  exit 1
}

usage() {
  cat >&2 <<'EOF'
Usage: scripts/release/scout-homebrew.sh --tag atlas-scout-vX.Y.Z [options]

Options:
  --tag TAG              Scout release tag. Defaults to GITHUB_REF_NAME.
  --output-dir DIR       Artifact output directory. Defaults to dist/scout-homebrew.
  --repository OWNER/REPO GitHub repository. Defaults to RebuildingAmerica/atlas.
EOF
}

repo_root() {
  git rev-parse --show-toplevel 2>/dev/null || die "must run inside the Atlas git repo"
}

pyproject_field() {
  file=$1
  field=$2
  awk -v field="$field" '
    /^\[project\]$/ { in_project = 1; next }
    in_project && /^\[/ { exit }
    in_project && $1 == field && $2 == "=" {
      value = $0
      sub(/^[^"]*"/, "", value)
      sub(/".*$/, "", value)
      print value
      exit
    }
  ' "$file"
}

validate_package() {
  expected_name=$1
  pyproject=$2
  expected_version=$3
  actual_name=$(pyproject_field "$pyproject" name)
  actual_version=$(pyproject_field "$pyproject" version)

  [ "$actual_name" = "$expected_name" ] ||
    die "$pyproject declares $actual_name, expected $expected_name"
  [ "$actual_version" = "$expected_version" ] ||
    die "$pyproject declares version $actual_version, expected $expected_version"
}

validate_versions() {
  version=$1
  validate_package atlas-shared libs/shared/pyproject.toml "$version"
  validate_package atlas-discovery-engine libs/discovery-engine/pyproject.toml "$version"
  validate_package atlas-scout scout/pyproject.toml "$version"
}

validate_tag() {
  tag=$1
  version=$(printf '%s\n' "$tag" |
    sed -nE 's/^atlas-scout-v([0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.-]+)?)$/\1/p')
  [ -n "$version" ] || die "Scout releases must use tags shaped like atlas-scout-v1.2.3"
  printf '%s\n' "$version"
}

ensure_release_paths_clean() {
  git diff --quiet -- LICENSE README.md libs/shared libs/discovery-engine scout ||
    die "release source paths have unstaged changes"
  git diff --cached --quiet -- LICENSE README.md libs/shared libs/discovery-engine scout ||
    die "release source paths have staged changes"
}

write_archive() {
  version=$1
  archive_path=$2
  prefix="atlas-scout-$version/"

  git archive \
    --format=tar \
    --prefix="$prefix" \
    HEAD \
    -- LICENSE README.md libs/shared libs/discovery-engine scout |
    gzip -n >"$archive_path"
}

write_formula() {
  version=$1
  release_url=$2
  sha256=$3
  resources_path=$4
  formula_path=$5

  {
    cat <<EOF
# Generated by scripts/release/scout-homebrew.sh for atlas-scout $version.
class AtlasScout < Formula
  include Language::Python::Virtualenv

  desc "Autonomous civic actor discovery CLI for Atlas"
  homepage "https://github.com/RebuildingAmerica/atlas"
  url "$release_url"
  sha256 "$sha256"
  license "MIT"

  depends_on "python@3.12"

EOF
    cat "$resources_path"
    cat <<'EOF'

  def install
    venv = virtualenv_create(libexec, "python3.12")
    venv.pip_install resources
    venv.pip_install buildpath/"libs/shared"
    venv.pip_install buildpath/"libs/discovery-engine"
    venv.pip_install buildpath/"scout"
    bin.install_symlink libexec/"bin/scout" => "scout"
  end

  def caveats
    <<~EOS
      Scout can use Playwright to read JavaScript-rendered pages when static fetches are not enough.
      Install Chromium when you need that fallback:
        #{libexec}/bin/playwright install chromium
    EOS
  end

  test do
    assert_match "Usage", shell_output("#{bin}/scout --help")
    assert_match "scout", shell_output("#{bin}/scout db path")
  end
end
EOF
  } >"$formula_path"
}

write_github_output() {
  [ -n "${GITHUB_OUTPUT:-}" ] || return 0
  {
    echo "version=$version"
    echo "tag=$tag"
    echo "archive=$archive_path"
    echo "checksum=$checksum_path"
    echo "formula=$formula_path"
    echo "sha256=$sha256"
    echo "url=$release_url"
  } >>"$GITHUB_OUTPUT"
}

tag=${GITHUB_REF_NAME:-}
output_dir=dist/scout-homebrew
repository=RebuildingAmerica/atlas

while [ "$#" -gt 0 ]; do
  case "$1" in
    --tag)
      [ "$#" -gt 1 ] || die "--tag requires a value"
      tag=$2
      shift 2
      ;;
    --tag=*)
      tag=${1#--tag=}
      shift
      ;;
    --output-dir)
      [ "$#" -gt 1 ] || die "--output-dir requires a value"
      output_dir=$2
      shift 2
      ;;
    --output-dir=*)
      output_dir=${1#--output-dir=}
      shift
      ;;
    --repository)
      [ "$#" -gt 1 ] || die "--repository requires a value"
      repository=$2
      shift 2
      ;;
    --repository=*)
      repository=${1#--repository=}
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage
      die "unknown argument: $1"
      ;;
  esac
done

[ -n "$tag" ] || die "--tag is required when GITHUB_REF_NAME is unset"
root=$(repo_root)
cd "$root"

version=$(validate_tag "$tag")
validate_versions "$version"
ensure_release_paths_clean

mkdir -p "$output_dir/Formula"
archive_path="$output_dir/atlas-scout-$version.tar.gz"
checksum_path="$archive_path.sha256"
formula_path="$output_dir/Formula/atlas-scout.rb"
release_url="https://github.com/$repository/releases/download/$tag/$(basename "$archive_path")"
tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

write_archive "$version" "$archive_path"
sha256=$(shasum -a 256 "$archive_path" | awk '{ print $1 }')
printf '%s\n' "$sha256" >"$checksum_path"
write_dependency_names "$tmp_dir/dependencies.txt" "$tmp_dir/requirements.txt"
write_resources "$tmp_dir/dependencies.txt" "$tmp_dir/resources.rb"
write_formula "$version" "$release_url" "$sha256" "$tmp_dir/resources.rb" "$formula_path"
write_github_output

echo "version=$version"
echo "archive=$archive_path"
echo "formula=$formula_path"
echo "sha256=$sha256"
