import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { formatEnvValuePromptMessage, summarizeEnvDoctor } from "./env.js";

void describe("bootstrap environment setup summary", () => {
  void it("treats env files as bootstrap-managed and only follows up on human values", () => {
    const summary = summarizeEnvDoctor(new Map());

    assert.equal(summary.success, false);
    assert.deepEqual(summary.followUpItems, [
      "Provide ANTHROPIC_API_KEY when bootstrap prompts for it.",
    ]);
    assert.match(summary.message, /ANTHROPIC_API_KEY — needed/);
    assert.match(
      summary.message,
      /ATLAS_AUTH_INTERNAL_SECRET — generated by setup/,
    );
    assert.doesNotMatch(summary.message, /\.env/);
    assert.equal(
      summary.followUpItems.some((item) => item.includes("Copy ")),
      false,
    );
  });

  void it("puts setup steps directly in human-provided value prompts", () => {
    const anthropic = formatEnvValuePromptMessage("ANTHROPIC_API_KEY");
    assert.match(
      anthropic,
      /Open https:\/\/console\.anthropic\.com\/settings\/keys/,
    );
    assert.match(anthropic, /Paste the value for ANTHROPIC_API_KEY here/);
    assert.match(anthropic, /Bootstrap writes this to \.env and API env files/);

    const resend = formatEnvValuePromptMessage("ATLAS_EMAIL_RESEND_API_KEY");
    assert.match(resend, /Open https:\/\/resend\.com\/api-keys/);
    assert.match(resend, /Verify the sender domain/);
    assert.match(resend, /leave blank to skip for now/);
  });
});
