import { existsSync, copyFileSync } from "node:fs";
import path from "node:path";
import { log, note, text, password } from "@clack/prompts";
import pc from "picocolors";
import type { PhaseResult } from "../state.js";
import { parseEnvFile, mergeEnvFile } from "../lib/env-file.js";
import { generateSecret, isPlaceholder } from "../lib/secret.js";
import { promptOrExit, logSubline } from "../lib/ui.js";
import type { ReadinessState } from "../state.js";
import { getVercelScope, detectAndLink, syncEnvVars } from "../lib/vercel.js";
import {
  buildVercelEnvVars,
  ensureProductionRoutingConfig,
  type HostedDeployTarget,
} from "./env-routing.js";

const AUTO_GENERATED_SECRETS = new Set([
  "ATLAS_AUTH_INTERNAL_SECRET",
  "ATLAS_EDGE_ORIGIN_SECRET",
]);

interface EnvKeyConfig {
  prompt: string;
  sensitive: boolean;
  hint: string;
  guidance: string[];
  writesTo: string;
  required: boolean;
  localOnly: boolean;
}

const PROMPTED_KEYS: Record<string, EnvKeyConfig> = {
  ANTHROPIC_API_KEY: {
    prompt: "Anthropic API key",
    sensitive: true,
    hint: "Create one at https://console.anthropic.com/settings/keys — you need a key with Claude API access.",
    guidance: [
      "Open https://console.anthropic.com/settings/keys.",
      "Create an API key for Atlas with Claude API access.",
      "Copy the key value once it is shown.",
    ],
    writesTo: ".env and API env files",
    required: true,
    localOnly: true,
  },
  ATLAS_EMAIL_RESEND_API_KEY: {
    prompt: "Resend API key",
    sensitive: true,
    hint: "Sign up at https://resend.com and create an API key. This is used to send magic-link sign-in emails. Leave blank to use the local email capture provider instead.",
    guidance: [
      "Open https://resend.com/api-keys.",
      "Verify the sender domain used by ATLAS_EMAIL_FROM if it is not verified yet.",
      "Create an API key that can send transactional email.",
      "Copy the key value once it is shown.",
    ],
    writesTo: ".env and Vercel when hosted sync is available",
    required: false,
    localOnly: false,
  },
  SEARCH_API_KEY: {
    prompt: "Search API key (Brave Search)",
    sensitive: true,
    hint: "Get a free key at https://brave.com/search/api/ — used by the discovery pipeline to find local civic actors. Leave blank to skip (discovery will still work but with fewer sources).",
    guidance: [
      "Open https://brave.com/search/api/.",
      "Create or open the Brave Search API subscription for Atlas.",
      "Copy the API key from the dashboard.",
    ],
    writesTo: ".env and API env files",
    required: false,
    localOnly: false,
  },
  OPENSTATUS_API_KEY: {
    prompt: "OpenStatus API key",
    sensitive: true,
    hint: "Get your API key from Settings → API Token at https://www.openstatus.dev/app/settings. Used to run synthetic monitors after every deploy via GitHub Actions. Leave blank to skip.",
    guidance: [
      "Open https://www.openstatus.dev/app/settings.",
      "Go to Settings > API Token.",
      "Create or reveal an API token for hosted synthetic monitors.",
      "Copy the token value.",
    ],
    writesTo: ".env.production",
    required: false,
    localOnly: false,
  },
};

interface EnvFileSpec {
  target: string;
  example: string;
  label: string;
}

interface EnvFilePreparation {
  created: number;
  ready: number;
  skipped: string[];
  wouldCreate: number;
}

export interface EnvDoctorSummary {
  success: boolean;
  followUpItems: string[];
  message: string;
}

function envValueReady(env: Map<string, string>, key: string): boolean {
  const value = env.get(key);
  return value !== undefined && !isPlaceholder(value);
}

export function summarizeEnvDoctor(env: Map<string, string>): EnvDoctorSummary {
  const followUpItems: string[] = [];
  const lines: string[] = ["Human-provided values"];

  for (const [key, config] of Object.entries(PROMPTED_KEYS)) {
    if (!config.required) continue;
    const ready = envValueReady(env, key);
    lines.push(`${key} — ${ready ? "ready" : "needed"}`);
    if (!ready) {
      followUpItems.push(`Provide ${key} when bootstrap prompts for it.`);
    }
  }

  lines.push("", "Generated by setup");
  for (const key of AUTO_GENERATED_SECRETS) {
    lines.push(
      `${key} — ${envValueReady(env, key) ? "ready" : "generated by setup"}`,
    );
  }

  return {
    success: followUpItems.length === 0,
    followUpItems,
    message: lines.join("\n"),
  };
}

export function formatEnvValuePromptMessage(key: string): string {
  const config = PROMPTED_KEYS[key];
  if (!config) {
    throw new Error(`No bootstrap prompt guidance configured for ${key}.`);
  }

  const lines = [
    config.prompt,
    "",
    ...config.guidance.map((step, index) => `${index + 1}. ${step}`),
    "",
    `Paste the value for ${key} here${config.required ? "." : ", or leave blank to skip for now."}`,
    `Bootstrap writes this to ${config.writesTo}.`,
  ];

  if (!config.required) {
    lines.push("You can rerun bootstrap later to fill it in.");
  }

  return lines.join("\n");
}

function prepareEnvFiles(
  projectRoot: string,
  envFiles: EnvFileSpec[],
  doctorMode: boolean,
): EnvFilePreparation {
  const result: EnvFilePreparation = {
    created: 0,
    ready: 0,
    skipped: [],
    wouldCreate: 0,
  };

  for (const spec of envFiles) {
    const targetPath = path.join(projectRoot, spec.target);
    const examplePath = path.join(projectRoot, spec.example);

    if (!existsSync(examplePath)) {
      result.skipped.push(spec.label);
      continue;
    }

    if (existsSync(targetPath)) {
      result.ready++;
      continue;
    }

    if (doctorMode) {
      result.wouldCreate++;
      continue;
    }

    copyFileSync(examplePath, targetPath);
    result.created++;
  }

  return result;
}

export async function runEnvPhase(
  projectRoot: string,
  doctorMode: boolean,
  state: ReadinessState,
  hostedTarget: HostedDeployTarget | null,
  assumeYes: boolean,
): Promise<PhaseResult> {
  const followUpItems: string[] = [];
  const rootEnvPath = path.join(projectRoot, ".env");
  const stagingEnvPath = path.join(projectRoot, ".env.staging");
  const prodEnvPath = path.join(projectRoot, ".env.production");

  const envFiles: EnvFileSpec[] = [
    { target: ".env", example: ".env.example", label: "Root .env" },
    {
      target: ".env.staging",
      example: ".env.staging.example",
      label: "Staging .env",
    },
    {
      target: ".env.production",
      example: ".env.production.example",
      label: "Production .env",
    },
    { target: "api/.env", example: "api/.env.example", label: "API .env" },
    {
      target: "app/.env.local",
      example: "app/.env.example",
      label: "App .env.local",
    },
  ];

  const envFilePreparation = prepareEnvFiles(projectRoot, envFiles, doctorMode);
  if (envFilePreparation.skipped.length > 0) {
    logSubline(
      pc.dim(
        `Skipped ${envFilePreparation.skipped.length} configuration template${envFilePreparation.skipped.length === 1 ? "" : "s"}`,
      ),
    );
  }

  if (doctorMode) {
    if (envFilePreparation.wouldCreate > 0) {
      log.info("Local configuration — setup will prepare it automatically");
    } else {
      log.success("Local configuration ready");
    }
    const summary = summarizeEnvDoctor(parseEnvFile(rootEnvPath));
    note(summary.message, "Setup values");
    return {
      success: summary.success,
      followUpItems: summary.followUpItems,
    };
  }

  if (envFilePreparation.created > 0) {
    log.success("Local configuration prepared");
  } else {
    log.success("Local configuration ready");
  }

  // Step 2: Auto-generate secrets
  const rootEnv = parseEnvFile(rootEnvPath);
  const updates = new Map<string, string>();

  for (const key of AUTO_GENERATED_SECRETS) {
    const current = rootEnv.get(key);
    if (!current || isPlaceholder(current)) {
      const secret = generateSecret();
      updates.set(key, secret);
      logSubline(`${key}: generated`);
    }
  }

  // Step 3: Prompt for keys that need user input
  for (const [key, config] of Object.entries(PROMPTED_KEYS)) {
    const current = rootEnv.get(key);
    if (current && !isPlaceholder(current)) continue;

    const value = await promptOrExit(
      config.sensitive
        ? password({
            message: formatEnvValuePromptMessage(key),
            validate: (v) => {
              if (config.required && !(v ?? "").trim()) {
                return `${config.prompt} is required.`;
              }
            },
          })
        : text({
            message: formatEnvValuePromptMessage(key),
            validate: (v) => {
              if (config.required && !(v ?? "").trim()) {
                return `${config.prompt} is required.`;
              }
            },
          }),
    );

    if (typeof value === "string" && value.trim()) {
      updates.set(key, value.trim());
    } else if (config.required) {
      followUpItems.push(`Set ${key} in .env — ${config.hint}`);
    }
  }

  if (hostedTarget) {
    await ensureProductionRoutingConfig(
      hostedTarget === "production" ? prodEnvPath : stagingEnvPath,
      followUpItems,
    );
  }

  // Step 5: Write updates
  if (updates.size > 0) {
    mergeEnvFile(rootEnvPath, updates);
    log.success("Setup values saved");
    logSubline(`${updates.size} value${updates.size === 1 ? "" : "s"} updated`);

    // Propagate shared keys to API and app env files
    const sharedKeys = [
      "ATLAS_AUTH_INTERNAL_SECRET",
      "ATLAS_EDGE_ORIGIN_SECRET",
      "ANTHROPIC_API_KEY",
    ];
    for (const envSpec of envFiles.slice(1)) {
      const targetPath = path.join(projectRoot, envSpec.target);
      if (!existsSync(targetPath)) continue;

      const envUpdates = new Map<string, string>();
      for (const key of sharedKeys) {
        const value = updates.get(key);
        if (value) envUpdates.set(key, value);
      }
      if (envUpdates.size > 0) {
        mergeEnvFile(targetPath, envUpdates);
      }
    }
  }

  // Step 6: Sync to Vercel if deploy-vercel capability is ready
  if (hostedTarget && state.capabilities["deploy-vercel"]?.status === "ready") {
    const appDir = path.join(projectRoot, "app");
    await detectAndLink(appDir, { assumeYes });

    const scope = getVercelScope(appDir);
    if (scope) {
      const productionEnv = getMergedEnv(rootEnvPath, prodEnvPath);
      const stagingEnv = getMergedEnv(rootEnvPath, stagingEnvPath);
      const varsToSync = buildVercelEnvVars(
        hostedTarget,
        productionEnv,
        stagingEnv,
      );
      const synced = await syncEnvVars(varsToSync, scope, {
        cwd: appDir,
      });
      if (!synced) {
        followUpItems.push(
          "Vercel env sync did not complete — run bootstrap again from a linked app/ directory",
        );
      }
    } else {
      followUpItems.push(
        "Vercel project not linked — run `vercel link` in app/ then re-run bootstrap",
      );
    }
  }

  return { success: true, followUpItems };
}

function getMergedEnv(
  rootEnvPath: string,
  prodEnvPath: string,
): Map<string, string> {
  const merged = parseEnvFile(rootEnvPath);
  for (const [key, value] of parseEnvFile(prodEnvPath)) {
    merged.set(key, value);
  }
  return merged;
}
