"""Search-term mappings for the autodiscovery pipeline."""

from __future__ import annotations

__all__ = ["ISSUE_SEARCH_TERMS"]

ISSUE_SEARCH_TERMS: dict[str, list[str]] = {
    # Economic Security
    "automation_and_ai_displacement": [
        "automation",
        "AI displacement",
        "job automation",
        "artificial intelligence jobs",
        "worker displacement",
        "technological unemployment",
        "workforce reskilling program",
        "WIOA workforce development",
        "algorithmic management",
        "deskilling automation",
        "future of work initiative",
    ],
    "gig_economy_and_precarious_work": [
        "gig economy",
        "gig workers",
        "contract workers",
        "precarious work",
        "temporary workers",
        "freelance workers",
        "independent contractor misclassification",
        "portable benefits",
        "platform worker organizing",
        "AB5 worker classification",
        "on-demand labor rights",
    ],
    "income_inequality_and_wealth_concentration": [
        "income inequality",
        "wealth gap",
        "wealth concentration",
        "wage gap",
        "economic inequality",
        "inequality",
        "living wage campaign",
        "EITC expansion",
        "wealth tax advocacy",
        "economic mobility initiative",
        "guaranteed income pilot",
    ],
    "healthcare_economics_and_medical_debt": [
        "medical debt",
        "healthcare costs",
        "health insurance",
        "healthcare affordability",
        "healthcare access",
        "medical bankruptcy",
        "surprise billing protections",
        "hospital price transparency",
        "charity care enrollment",
        "medical debt abolition",
        "No Surprises Act advocacy",
    ],
    "student_debt_and_college_affordability": [
        "student debt",
        "student loans",
        "college affordability",
        "higher education costs",
        "student loan forgiveness",
        "education affordability",
        "income-driven repayment",
        "PSLF public service loan forgiveness",
        "predatory lending for-profit college",
        "free college tuition program",
        "IDR plan advocacy",
    ],
    # Housing and the Built Environment
    "housing_affordability": [
        "affordable housing",
        "housing crisis",
        "rent",
        "housing affordability",
        "community land trust",
        "tenant organizing",
        "rental housing",
        "inclusionary zoning",
        "LIHTC low-income housing tax credit",
        "Section 8 voucher advocacy",
        "right to counsel eviction",
        "YIMBY housing advocacy",
    ],
    "suburban_sprawl_and_car_dependency": [
        "suburban sprawl",
        "car dependency",
        "urban sprawl",
        "land use",
        "car culture",
        "sprawl",
        "form-based code",
        "transit-oriented development TOD",
        "complete streets advocacy",
        "missing middle housing",
        "15-minute city walkability",
    ],
    "homelessness_and_housing_insecurity": [
        "homelessness",
        "housing insecurity",
        "unhoused",
        "housing instability",
        "homeless services",
        "Housing First program",
        "continuum of care CoC",
        "permanent supportive housing",
        "HMIS homeless management",
        "street outreach encampment",
    ],
    "zoning_and_land_use": [
        "zoning",
        "land use",
        "zoning reform",
        "zoning policy",
        "urban planning",
        "land use planning",
        "upzoning densification",
        "ADU accessory dwelling unit",
        "comprehensive plan update",
        "variance conditional use permit",
        "exclusionary zoning abolition",
    ],
    # Climate and Environment
    "climate_adaptation_and_resilience": [
        "climate adaptation",
        "climate resilience",
        "climate change",
        "climate preparedness",
        "climate impacts",
        "climate action plan CAP",
        "managed retreat floodplain",
        "resilience hub community",
        "FEMA hazard mitigation planning",
        "climate vulnerability assessment",
    ],
    "environmental_justice_and_pollution": [
        "environmental justice",
        "pollution",
        "environmental racism",
        "toxic pollution",
        "air quality",
        "environmental health",
        "EJ screen cumulative impacts",
        "frontline community organizing",
        "sacrifice zone pollution",
        "NEPA environmental review",
        "Title VI environmental complaint",
    ],
    "sustainable_agriculture_and_food_systems": [
        "sustainable agriculture",
        "local food",
        "food security",
        "food systems",
        "agricultural sustainability",
        "urban farming",
        "food sovereignty movement",
        "CSA community supported agriculture",
        "food policy council",
        "SNAP double up bucks",
        "regenerative agriculture advocacy",
    ],
    "water_access_and_infrastructure": [
        "water access",
        "water quality",
        "water infrastructure",
        "drinking water",
        "water systems",
        "clean water",
        "PFAS contamination remediation",
        "lead service line replacement",
        "water affordability shutoff",
        "SDWA safe drinking water act",
        "water equity coalition",
    ],
    "energy_transition": [
        "renewable energy",
        "energy transition",
        "clean energy",
        "solar",
        "wind energy",
        "just energy transition",
        "community solar program",
        "IRA clean energy incentives",
        "energy democracy cooperative",
        "fossil fuel divestment campaign",
        "electrification building decarbonization",
    ],
    # Democracy and Governance
    "voter_suppression_and_electoral_access": [
        "voter suppression",
        "voting rights",
        "electoral access",
        "voter registration",
        "voting access",
        "VRA Voting Rights Act enforcement",
        "voter ID law challenge",
        "automatic voter registration AVR",
        "poll worker recruitment",
        "vote-by-mail expansion advocacy",
    ],
    "local_government_and_civic_engagement": [
        "local government",
        "civic engagement",
        "community organizing",
        "local politics",
        "community participation",
        "participatory budgeting",
        "community benefits agreement CBA",
        "neighborhood council advocacy",
        "civic tech open government",
        "power building base building",
    ],
    "political_polarization_and_democratic_norms": [
        "political polarization",
        "democratic norms",
        "institutional health",
        "polarization",
        "democratic institutions",
        "depolarization bridging divides",
        "deliberative democracy dialogue",
        "cross-partisan coalition",
        "democratic backsliding accountability",
    ],
    "money_in_politics": [
        "campaign finance",
        "money in politics",
        "political donations",
        "lobbying",
        "dark money",
        "Citizens United overturn",
        "public campaign financing",
        "lobbying disclosure reform",
        "super PAC transparency",
        "small donor matching program",
    ],
    "electoral_reform": [
        "electoral reform",
        "voting systems",
        "election administration",
        "election reform",
        "representation",
        "ranked choice voting RCV",
        "proportional representation advocacy",
        "independent redistricting commission",
        "gerrymandering reform",
        "open primary nonpartisan election",
    ],
    # Technology and Information
    "social_media_and_mental_health": [
        "social media",
        "mental health",
        "digital mental health",
        "social media mental health",
        "tech and mental health",
        "screen time youth advocacy",
        "age verification online safety",
        "KOSA Kids Online Safety Act",
        "algorithmic feed harm",
        "digital wellness program",
    ],
    "misinformation_and_epistemic_crisis": [
        "misinformation",
        "disinformation",
        "fake news",
        "information ecosystem",
        "epistemic crisis",
        "media literacy education",
        "fact-checking organization",
        "content moderation policy",
        "prebunking inoculation campaign",
        "trusted messenger initiative",
    ],
    "digital_privacy_and_surveillance": [
        "digital privacy",
        "surveillance",
        "privacy rights",
        "data privacy",
        "data protection",
        "facial recognition ban campaign",
        "CCPA GDPR consumer privacy",
        "data broker regulation",
        "predictive policing surveillance",
        "digital rights advocacy EFF",
    ],
    "broadband_access_and_digital_divide": [
        "broadband access",
        "digital divide",
        "internet access",
        "broadband",
        "digital equity",
        "BEAD broadband equity program",
        "digital navigator program",
        "ACP affordable connectivity",
        "municipal broadband",
        "digital inclusion coalition",
    ],
    "platform_monopolies_and_tech_accountability": [
        "platform monopolies",
        "tech monopolies",
        "big tech",
        "tech accountability",
        "platform regulation",
        "antitrust tech enforcement",
        "interoperability data portability",
        "Section 230 reform",
        "algorithmic accountability act",
        "tech worker organizing",
    ],
}
