"""Search-term mappings for the autodiscovery pipeline."""

from __future__ import annotations

__all__ = ["ISSUE_SEARCH_TERMS"]

ISSUE_SEARCH_TERMS: dict[str, list[str]] = {
    # Education
    "k12_education_inequality": [
        "K-12 education",
        "education inequality",
        "school inequality",
        "education equity",
        "school funding",
        "Title I school funding advocacy",
        "school segregation integration",
        "weighted student funding formula",
        "community schools initiative",
        "school-to-prison pipeline intervention",
    ],
    "higher_education_affordability": [
        "higher education",
        "college affordability",
        "university",
        "college access",
        "college completion",
        "Pell Grant expansion",
        "OER open educational resources",
        "college promise scholarship program",
        "FAFSA simplification advocacy",
        "first-generation college access",
    ],
    "vocational_and_alternative_pathways": [
        "vocational training",
        "apprenticeships",
        "alternative education",
        "skills training",
        "trade school",
        "registered apprenticeship program",
        "CTE career technical education",
        "earn and learn pathway",
        "pre-apprenticeship pipeline",
        "stackable credentials workforce",
    ],
    "education_funding_and_policy": [
        "education policy",
        "education funding",
        "school policy",
        "education reform",
        "school board advocacy organizing",
        "ESSA accountability plan",
        "per-pupil spending equity",
        "charter school accountability",
        "education budget campaign",
    ],
    # Health and Social Connection
    "mental_health_crisis_and_access": [
        "mental health",
        "mental illness",
        "mental health services",
        "mental health crisis",
        "depression",
        "988 crisis hotline advocacy",
        "CCBHC certified behavioral health",
        "mental health parity enforcement",
        "peer support specialist program",
        "crisis intervention team CIT",
    ],
    "loneliness_and_social_isolation": [
        "loneliness",
        "social isolation",
        "social connection",
        "community",
        "belonging",
        "third place community gathering",
        "social cohesion placemaking",
        "loneliness epidemic intervention",
        "mutual aid network",
        "intergenerational programming",
    ],
    "addiction_and_harm_reduction": [
        "addiction",
        "substance abuse",
        "harm reduction",
        "opioid",
        "drug treatment",
        "naloxone distribution program",
        "MAT medication-assisted treatment",
        "syringe services program",
        "safe consumption site advocacy",
        "recovery community organization",
    ],
    "healthcare_access_and_coverage": [
        "healthcare access",
        "health insurance",
        "healthcare coverage",
        "health equity",
        "uninsured",
        "Medicaid expansion advocacy",
        "FQHC federally qualified health center",
        "navigator enrollment assister",
        "single-payer Medicare for All",
        "coverage gap uncompensated care",
    ],
    "community_health_infrastructure": [
        "community health",
        "public health",
        "health clinics",
        "health infrastructure",
        "primary care",
        "community health worker CHW",
        "social determinants of health SDOH",
        "health department capacity building",
        "mobile health clinic outreach",
        "health impact assessment",
    ],
    # Infrastructure and Public Goods
    "transportation_and_mobility": [
        "transportation",
        "transit",
        "public transportation",
        "bus",
        "bike infrastructure",
        "pedestrian",
        "Vision Zero traffic safety",
        "micromobility bike share",
        "ADA paratransit accessibility",
        "transportation demand management TDM",
        "multimodal transportation planning",
    ],
    "public_transit": [
        "public transit",
        "transit system",
        "bus rapid transit",
        "light rail",
        "transit equity",
        "fare-free transit campaign",
        "transit riders union",
        "BRT bus rapid transit expansion",
        "frequency-based network redesign",
        "first mile last mile solution",
    ],
    "broadband_and_digital_access": [
        "broadband infrastructure",
        "broadband access",
        "internet infrastructure",
        "fiber optic",
        "municipal broadband network",
        "BEAD infrastructure deployment",
        "digital literacy training",
        "last mile connectivity rural",
        "open access fiber network",
    ],
    "water_infrastructure": [
        "water infrastructure",
        "water systems",
        "pipe",
        "water main",
        "water service",
        "lead pipe replacement program",
        "stormwater green infrastructure",
        "combined sewer overflow CSO",
        "water utility rate reform",
        "asset management capital improvement",
    ],
    "physical_infrastructure_decay": [
        "infrastructure",
        "infrastructure decay",
        "infrastructure maintenance",
        "roads",
        "bridges",
        "IIJA infrastructure investment",
        "structurally deficient bridge",
        "capital improvement plan CIP",
        "deferred maintenance backlog",
        "infrastructure report card ASCE",
    ],
    # Justice and Public Safety
    "criminal_justice_reform_and_mass_incarceration": [
        "criminal justice reform",
        "mass incarceration",
        "incarceration",
        "justice reform",
        "sentencing reform",
        "bail reform cash bail abolition",
        "reentry program formerly incarcerated",
        "decarceration prison reduction",
        "prosecutorial accountability reform",
        "ban the box fair chance hiring",
    ],
    "policing_and_community_safety": [
        "policing",
        "police reform",
        "community safety",
        "public safety",
        "police accountability",
        "civilian oversight review board",
        "community violence intervention CVI",
        "use of force policy reform",
        "consent decree police department",
        "non-police crisis response",
    ],
    "immigration_and_belonging": [
        "immigration",
        "immigrant rights",
        "immigration policy",
        "deportation",
        "immigrant communities",
        "DACA TPS immigration status",
        "sanctuary city policy",
        "immigrant legal defense fund",
        "know your rights immigration",
        "welcoming city refugee resettlement",
    ],
    "restorative_justice": [
        "restorative justice",
        "conflict resolution",
        "community justice",
        "healing justice",
        "restorative practices school discipline",
        "victim-offender mediation",
        "circle process peacemaking",
        "transformative justice organizing",
        "diversion program alternative sentencing",
    ],
    # Rural-Urban Divide
    "rural_economic_decline_and_brain_drain": [
        "rural economy",
        "rural economic decline",
        "brain drain",
        "rural jobs",
        "rural development",
        "USDA rural development grant",
        "opportunity zone rural investment",
        "main street revitalization",
        "rural broadband economic anchor",
        "place-based rural strategy",
    ],
    "cultural_resentment_and_political_division": [
        "rural urban divide",
        "cultural resentment",
        "political division",
        "rural urban split",
        "bridging rural urban dialogue",
        "civic listening tour",
        "cross-cultural exchange program",
        "rural identity narrative project",
    ],
    "rural_healthcare_and_services": [
        "rural healthcare",
        "rural health",
        "rural services",
        "rural clinics",
        "critical access hospital CAH",
        "telehealth rural expansion",
        "NHSC rural provider shortage",
        "rural EMS ambulance crisis",
        "rural maternity care desert",
    ],
    "urban_rural_coalition_building": [
        "urban rural coalition",
        "cross community organizing",
        "coalition building",
        "rural-urban solidarity network",
        "regional equity collaborative",
        "food-farm-city linkage",
        "multi-county partnership initiative",
        "anchor institution rural engagement",
    ],
    # Labor and Worker Power
    "union_organizing": [
        "union organizing",
        "unionization",
        "labor organizing",
        "collective bargaining",
        "labor movement",
        "NLRB union election",
        "card check neutrality agreement",
        "right to organize PRO Act",
        "union density campaign",
        "sectoral bargaining advocacy",
    ],
    "worker_cooperatives": [
        "worker cooperative",
        "worker-owned",
        "co-op",
        "cooperative enterprise",
        "employee ownership",
        "ESOP employee stock ownership",
        "cooperative development center",
        "democratic workplace governance",
        "cooperative conversion buyout",
        "solidarity economy network",
    ],
    "workplace_safety_and_conditions": [
        "workplace safety",
        "workplace conditions",
        "occupational health",
        "worker safety",
        "OSHA",
        "OSHA whistleblower complaint",
        "heat stress workplace protection",
        "ergonomics injury prevention",
        "worker center safety training",
        "workplace fatality investigation",
    ],
    "wage_theft_and_labor_rights": [
        "wage theft",
        "labor rights",
        "worker rights",
        "wage violations",
        "labor standards",
        "wage claim enforcement",
        "minimum wage fight for 15",
        "worker center labor advocacy",
        "prevailing wage enforcement",
        "payroll fraud misclassification",
    ],
    "just_transition": [
        "just transition",
        "energy transition",
        "worker transition",
        "transitional support",
        "displaced worker retraining",
        "coal community transition fund",
        "economic diversification fossil fuel",
        "green jobs workforce pipeline",
        "community transition planning",
    ],
}
