"""OpenAPI schema descriptions for the Atlas API."""

from __future__ import annotations

SchemaPropertyKey = tuple[str, str]

SCHEMA_DESCRIPTIONS = {
    "HTTPValidationError": "Validation failure returned when a request cannot be parsed.",
    "ValidationError": "One field-level validation problem inside an invalid request.",
}

SCHEMA_PROPERTY_DESCRIPTIONS: dict[SchemaPropertyKey, str] = {
    ("ClaimEvidenceSet", "contact"): "Contact evidence used to support the profile claim.",
    ("ClaimEvidenceSet", "issues"): "Issue-area evidence associated with the claimed profile.",
    ("ClaimEvidenceSet", "place"): "Place evidence associated with the claimed profile.",
    ("ClaimEvidenceSet", "summary"): "Short evidence summary reviewers can inspect.",
    ("CoverageReportResponse", "summary"): "Top-level coverage report metrics and context.",
    ("CoverageTargetDetailResponse", "target"): "Coverage target being reviewed or updated.",
    ("CoverageUnderwritingReportResponse", "data_boundary"): "Limits on what the report proves.",
    (
        "CoverageUnderwritingReportResponse",
        "public_impact",
    ): "Public coverage outcomes for the report.",
    ("CoverageUnderwritingReportResponse", "summary"): "Funder-facing coverage report summary.",
    (
        "DirectoryConfigRequest",
        "methodology",
    ): "Public methodology text for the workspace directory.",
    ("DirectoryConfigRequest", "scope"): "Public scope text for the workspace directory.",
    ("DirectoryConfigResponse", "methodology"): "Saved public methodology text.",
    ("DirectoryConfigResponse", "scope"): "Saved public scope text.",
    ("DirectoryTemplateResponse", "place_scope"): "Place scope seeded by this directory template.",
    ("EntityCollectionResponse", "place"): "Place context for place-scoped entity results.",
    ("EntityCreateRequest", "address"): "Public address or geography for the new actor.",
    ("EntityCreateRequest", "contact"): "Public contact channels for the new actor.",
    ("EntityDetailResponse", "actor_quality"): "Quality signals for the actor record.",
    ("EntityDetailResponse", "address"): "Normalized public address or geography for the actor.",
    ("EntityDetailResponse", "claim"): "Subject-claim state for this actor profile.",
    ("EntityDetailResponse", "claim_evidence"): "Evidence considered for the profile claim.",
    ("EntityDetailResponse", "contact"): "Public contact channels for the actor.",
    ("EntityDetailResponse", "flag_summary"): "Open correction signals on this actor.",
    ("EntityDetailResponse", "freshness"): "Source freshness and last-seen context for the actor.",
    ("EntityDetailResponse", "profile_answers"): "Subject-managed profile answers.",
    ("EntityDetailResponse", "trust"): "Trust tier and provenance summary for the actor.",
    ("EntityResponse", "actor_quality"): "Quality signals for the actor record.",
    ("EntityResponse", "address"): "Normalized public address or geography for the actor.",
    ("EntityResponse", "claim"): "Subject-claim state for this actor profile.",
    ("EntityResponse", "claim_evidence"): "Evidence considered for the profile claim.",
    ("EntityResponse", "contact"): "Public contact channels for the actor.",
    ("EntityResponse", "flag_summary"): "Open correction signals on this actor.",
    ("EntityResponse", "freshness"): "Source freshness and last-seen context for the actor.",
    ("EntityResponse", "profile_answers"): "Subject-managed profile answers.",
    ("EntityResponse", "trust"): "Trust tier and provenance summary for the actor.",
    ("EntityUpdateRequest", "address"): "Public address or geography updates for the actor.",
    ("EntityUpdateRequest", "contact"): "Public contact channel updates for the actor.",
    ("IssueSignalsResponse", "place"): "Place context for the issue-signal summary.",
    ("MapPoint", "geo_specificity"): "How local or broad the actor's geography is.",
    ("MapPoint", "geocode_precision"): "Precision tier used for the map coordinate.",
    ("MapPoint", "geocode_source"): "Source used to derive the map coordinate.",
    ("MapPoint", "latest_source_date"): "Newest source date represented on the map point.",
    ("MapPoint", "place_label"): "Human-readable place label for the map point.",
    ("MapPoint", "source_count"): "Number of sources linked to the mapped actor.",
    ("OrgBriefCreateRequest", "confidence_summary"): "Confidence notes captured with the brief.",
    ("OrgBriefCreateRequest", "scope"): "Research scope for the new brief.",
    ("OrgBriefExportResponse", "brief"): "Brief artifact being exported.",
    ("OrgBriefExportResponse", "provenance"): "Source and export provenance for the brief.",
    ("OrgBriefResponse", "confidence_summary"): "Confidence notes saved with the brief.",
    ("OrgBriefResponse", "scope"): "Research scope saved with the brief.",
    ("OrgBriefUpdateRequest", "confidence_summary"): "Updated confidence notes for the brief.",
    (
        "OrgIntegrationMonitoringResponse",
        "data_boundary",
    ): "Limits on workspace integration activity data.",
    ("OrgQualitySummaryResponse", "data_boundary"): "Limits on the workspace quality summary.",
    ("OrgQualitySummaryResponse", "duplicate_risk"): "Duplicate-risk signals for workspace data.",
    ("OrgQualitySummaryResponse", "source_coverage"): "Source coverage signals for workspace data.",
    ("OrgQualitySummaryResponse", "stale_records"): "Stale-record signals for workspace data.",
    ("OrgRenewalPacketResponse", "data_boundary"): "Limits on renewal-packet data.",
    ("OrgRenewalPacketResponse", "summary"): "Customer-safe renewal summary.",
    ("OrgUsageAuditLogResponse", "data_boundary"): "Limits on audit-log data.",
    ("OrgUsageSummaryResponse", "renewal_signals"): "Usage signals suitable for renewal review.",
    ("OrgWatchStatusResponse", "watch"): "Workspace watch state for the requested resource.",
    ("PlaceCoverageResponse", "place"): "Place context for the coverage summary.",
    ("PlaceGovernmentLinkResponse", "href"): "URL for the government or public-body link.",
    ("PlaceGovernmentLinkResponse", "label"): "Display label for the government link.",
    ("PlaceGovernmentResponse", "links"): "Public links associated with this government body.",
    ("PlaceGovernmentResponse", "name"): "Government or regional public body name.",
    ("PlaceGovernmentResponse", "role"): "Role this body plays for the place.",
    ("PlaceIdentityResponse", "place"): "Canonical Atlas place resource.",
    ("PlacePageContextResponse", "display"): "Human-readable display name for the place page.",
    ("PlacePageContextResponse", "governments"): "Relevant public bodies for the place.",
    ("PlacePageContextResponse", "kind"): "Place kind used by the public page.",
    ("PlacePageContextResponse", "name"): "Canonical place name.",
    ("PlacePageContextResponse", "place_key"): "Stable Atlas place key.",
    ("PlacePageContextResponse", "places"): "Related places shown in the page context.",
    ("PlacePageContextResponse", "resource_uri"): "Canonical resource URI for the place.",
    ("PlacePageContextResponse", "scopes"): "Broader or narrower scopes for the place.",
    ("PlaceProfileResponse", "place"): "Place context for the demographic profile.",
    ("PublicDirectoryResponse", "federation"): "Federation metadata for the public directory.",
    ("PublicDirectoryResponse", "methodology"): "Public methodology text for the directory.",
    (
        "PublicDirectoryResponse",
        "publication",
    ): "Publication state and timestamps for the directory.",
    ("PublicDirectoryResponse", "scope"): "Public scope text for the directory.",
    ("PublicDirectoryResponse", "stats"): "Published record counts for the directory.",
    (
        "PublicDirectoryResponse",
        "trust_footer",
    ): "Trust and provenance text shown with the directory.",
    ("PublicDirectoryResponse", "workspace"): "Public workspace identity for the directory.",
    ("PublicDirectoryWorkspace", "custom_domain"): "Verified custom domain for the directory.",
    ("SavedListExportItemResponse", "entry"): "Actor included in the saved-list export.",
    ("SavedListExportResponse", "list"): "Saved list metadata for the export.",
    ("SavedListExportResponse", "provenance"): "Source-count provenance for the saved-list export.",
    ("SavedListItemResponse", "entry"): "Actor included in the saved list.",
    ("SourceCollectionResponse", "place"): "Place context for place-scoped source results.",
    ("SourceResponse", "flag_summary"): "Open correction signals on this source.",
    ("SourceResponse", "freshness"): "Freshness context for this source.",
    ("WatchDigestItem", "entry"): "Actor associated with the watch digest item.",
    ("WatchDigestItem", "source"): "Source associated with the watch digest item.",
}
