/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FirehoseDotrssRouteImport } from './routes/firehose[.]rss'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DeviceTokenRouteImport } from './routes/device/token'
import { Route as DeviceStatusRouteImport } from './routes/device/status'
import { Route as DeviceDenyRouteImport } from './routes/device/deny'
import { Route as DeviceCodeRouteImport } from './routes/device/code'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as WorkspaceWatchingRouteImport } from './routes/_workspace/watching'
import { Route as WorkspaceOrganizationRouteImport } from './routes/_workspace/organization'
import { Route as WorkspaceListsRouteImport } from './routes/_workspace/lists'
import { Route as WorkspaceHomeRouteImport } from './routes/_workspace/home'
import { Route as WorkspaceFeedRouteImport } from './routes/_workspace/feed'
import { Route as WorkspaceDiscoveryRouteImport } from './routes/_workspace/discovery'
import { Route as WorkspaceCoverageRouteImport } from './routes/_workspace/coverage'
import { Route as WorkspaceCheckoutCompleteRouteImport } from './routes/_workspace/checkout-complete'
import { Route as WorkspaceBriefsRouteImport } from './routes/_workspace/briefs'
import { Route as WorkspaceAccountRouteImport } from './routes/_workspace/account'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicSecurityRouteImport } from './routes/_public/security'
import { Route as PublicRequestDiscountRouteImport } from './routes/_public/request-discount'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicPostLogoutRouteImport } from './routes/_public/post-logout'
import { Route as PublicMapRouteImport } from './routes/_public/map'
import { Route as PublicFirehoseRouteImport } from './routes/_public/firehose'
import { Route as PublicBrowseRouteImport } from './routes/_public/browse'
import { Route as AuthStartRouteImport } from './routes/_auth/start'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthDeviceRouteImport } from './routes/_auth/device'
import { Route as WorkspaceOrganizationIndexRouteImport } from './routes/_workspace/organization/index'
import { Route as WorkspaceAdminIndexRouteImport } from './routes/_workspace/admin/index'
import { Route as PublicProfilesIndexRouteImport } from './routes/_public/profiles/index'
import { Route as AuthDeviceIndexRouteImport } from './routes/_auth/device/index'
import { Route as DotwellKnownOauthProtectedResourceIndexRouteImport } from './routes/[.]well-known/oauth-protected-resource/index'
import { Route as DotwellKnownOauthAuthorizationServerIndexRouteImport } from './routes/[.]well-known/oauth-authorization-server/index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceOrganizationSsoRouteImport } from './routes/_workspace/organization/sso'
import { Route as WorkspaceManageSlugRouteImport } from './routes/_workspace/manage/$slug'
import { Route as WorkspaceListsIdRouteImport } from './routes/_workspace/lists/$id'
import { Route as WorkspaceCoverageTargetIdRouteImport } from './routes/_workspace/coverage/$targetId'
import { Route as WorkspaceBriefsNewRouteImport } from './routes/_workspace/briefs/new'
import { Route as WorkspaceBriefsBriefIdRouteImport } from './routes/_workspace/briefs/$briefId'
import { Route as WorkspaceAdminProfileClaimsRouteImport } from './routes/_workspace/admin/profile-claims'
import { Route as WorkspaceAdminDiscountsRouteImport } from './routes/_workspace/admin/discounts'
import { Route as WorkspaceAdminCloudCostsRouteImport } from './routes/_workspace/admin/cloud-costs'
import { Route as PublicProfilesPeopleRouteImport } from './routes/_public/profiles/people'
import { Route as PublicProfilesOrganizationsRouteImport } from './routes/_public/profiles/organizations'
import { Route as PublicPlacesPlaceSlugRouteImport } from './routes/_public/places/$placeSlug'
import { Route as PublicFeedbackSlugRouteImport } from './routes/_public/feedback/$slug'
import { Route as PublicEntriesEntryIdRouteImport } from './routes/_public/entries/$entryId'
import { Route as PublicDirectoriesOrgIdRouteImport } from './routes/_public/directories/$orgId'
import { Route as PublicClaimSlugRouteImport } from './routes/_public/claim/$slug'
import { Route as AuthStartCompleteRouteImport } from './routes/_auth/start/complete'
import { Route as AuthOauthConsentRouteImport } from './routes/_auth/oauth/consent'
import { Route as AuthDeviceApprovedRouteImport } from './routes/_auth/device/approved'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/_auth/accept-invitation/$invitationId'
import { Route as DotwellKnownOauthProtectedResourceMcpRouteImport } from './routes/[.]well-known/oauth-protected-resource/mcp'
import { Route as PublicProfilesPeopleIndexRouteImport } from './routes/_public/profiles/people/index'
import { Route as PublicProfilesOrganizationsIndexRouteImport } from './routes/_public/profiles/organizations/index'
import { Route as ApiAuthInternalApiKeyRouteImport } from './routes/api/auth/internal/api-key'
import { Route as ApiAtprotoOauthStartRouteImport } from './routes/api/atproto/oauth/start'
import { Route as ApiAtprotoOauthClientMetadataDotjsonRouteImport } from './routes/api/atproto/oauth/client-metadata[.]json'
import { Route as ApiAtprotoOauthCallbackRouteImport } from './routes/api/atproto/oauth/callback'
import { Route as PublicProfilesPeopleSlugRouteImport } from './routes/_public/profiles/people/$slug'
import { Route as PublicProfilesOrganizationsSlugRouteImport } from './routes/_public/profiles/organizations/$slug'
import { Route as PublicProfilesInitiativesSlugRouteImport } from './routes/_public/profiles/initiatives/$slug'
import { Route as PublicProfilesEventsSlugRouteImport } from './routes/_public/profiles/events/$slug'
import { Route as PublicProfilesCampaignsSlugRouteImport } from './routes/_public/profiles/campaigns/$slug'
import { Route as PublicPlacesPolitiesPlaceSlugRouteImport } from './routes/_public/places/polities/$placeSlug'
import { Route as PublicPlacesNeighborhoodsPlaceSlugRouteImport } from './routes/_public/places/neighborhoods/$placeSlug'
import { Route as PublicPlacesMetrosPlaceSlugRouteImport } from './routes/_public/places/metros/$placeSlug'
import { Route as PublicPlacesDistrictsPlaceSlugRouteImport } from './routes/_public/places/districts/$placeSlug'
import { Route as PublicPlacesCountiesPlaceSlugRouteImport } from './routes/_public/places/counties/$placeSlug'
import { Route as PublicPlacesCitiesPlaceSlugRouteImport } from './routes/_public/places/cities/$placeSlug'
import { Route as PublicPlacesBoroughsPlaceSlugRouteImport } from './routes/_public/places/boroughs/$placeSlug'
import { Route as DotwellKnownOauthAuthorizationServerApiAuthRouteImport } from './routes/[.]well-known/oauth-authorization-server/api/auth'
import { Route as ApiAtprotoOauthHarnessAuthorizeRouteImport } from './routes/api/atproto/oauth/harness/authorize'
import { Route as ApiAuthInternalMembershipsOrganizationIdMembersUserIdRouteImport } from './routes/api/auth/internal/memberships/$organizationId/members/$userId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FirehoseDotrssRoute = FirehoseDotrssRouteImport.update({
  id: '/firehose.rss',
  path: '/firehose.rss',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DeviceTokenRoute = DeviceTokenRouteImport.update({
  id: '/device/token',
  path: '/device/token',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceStatusRoute = DeviceStatusRouteImport.update({
  id: '/device/status',
  path: '/device/status',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceDenyRoute = DeviceDenyRouteImport.update({
  id: '/device/deny',
  path: '/device/deny',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceCodeRoute = DeviceCodeRouteImport.update({
  id: '/device/code',
  path: '/device/code',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/device/approve',
  path: '/device/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWatchingRoute = WorkspaceWatchingRouteImport.update({
  id: '/watching',
  path: '/watching',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOrganizationRoute = WorkspaceOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceListsRoute = WorkspaceListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceHomeRoute = WorkspaceHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceFeedRoute = WorkspaceFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDiscoveryRoute = WorkspaceDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCoverageRoute = WorkspaceCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCheckoutCompleteRoute =
  WorkspaceCheckoutCompleteRouteImport.update({
    id: '/checkout-complete',
    path: '/checkout-complete',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceBriefsRoute = WorkspaceBriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAccountRoute = WorkspaceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSecurityRoute = PublicSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRequestDiscountRoute = PublicRequestDiscountRouteImport.update({
  id: '/request-discount',
  path: '/request-discount',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPostLogoutRoute = PublicPostLogoutRouteImport.update({
  id: '/post-logout',
  path: '/post-logout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMapRoute = PublicMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFirehoseRoute = PublicFirehoseRouteImport.update({
  id: '/firehose',
  path: '/firehose',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBrowseRoute = PublicBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => PublicRoute,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AuthRoute,
} as any)
const WorkspaceOrganizationIndexRoute =
  WorkspaceOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceOrganizationRoute,
  } as any)
const WorkspaceAdminIndexRoute = WorkspaceAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicProfilesIndexRoute = PublicProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthDeviceIndexRoute = AuthDeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDeviceRoute,
} as any)
const DotwellKnownOauthProtectedResourceIndexRoute =
  DotwellKnownOauthProtectedResourceIndexRouteImport.update({
    id: '/.well-known/oauth-protected-resource/',
    path: '/.well-known/oauth-protected-resource/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerIndexRoute =
  DotwellKnownOauthAuthorizationServerIndexRouteImport.update({
    id: '/.well-known/oauth-authorization-server/',
    path: '/.well-known/oauth-authorization-server/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceOrganizationSsoRoute =
  WorkspaceOrganizationSsoRouteImport.update({
    id: '/sso',
    path: '/sso',
    getParentRoute: () => WorkspaceOrganizationRoute,
  } as any)
const WorkspaceManageSlugRoute = WorkspaceManageSlugRouteImport.update({
  id: '/manage/$slug',
  path: '/manage/$slug',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceListsIdRoute = WorkspaceListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkspaceListsRoute,
} as any)
const WorkspaceCoverageTargetIdRoute =
  WorkspaceCoverageTargetIdRouteImport.update({
    id: '/$targetId',
    path: '/$targetId',
    getParentRoute: () => WorkspaceCoverageRoute,
  } as any)
const WorkspaceBriefsNewRoute = WorkspaceBriefsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspaceBriefsRoute,
} as any)
const WorkspaceBriefsBriefIdRoute = WorkspaceBriefsBriefIdRouteImport.update({
  id: '/$briefId',
  path: '/$briefId',
  getParentRoute: () => WorkspaceBriefsRoute,
} as any)
const WorkspaceAdminProfileClaimsRoute =
  WorkspaceAdminProfileClaimsRouteImport.update({
    id: '/admin/profile-claims',
    path: '/admin/profile-claims',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceAdminDiscountsRoute = WorkspaceAdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAdminCloudCostsRoute =
  WorkspaceAdminCloudCostsRouteImport.update({
    id: '/admin/cloud-costs',
    path: '/admin/cloud-costs',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const PublicProfilesPeopleRoute = PublicProfilesPeopleRouteImport.update({
  id: '/profiles/people',
  path: '/profiles/people',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfilesOrganizationsRoute =
  PublicProfilesOrganizationsRouteImport.update({
    id: '/profiles/organizations',
    path: '/profiles/organizations',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesPlaceSlugRoute = PublicPlacesPlaceSlugRouteImport.update({
  id: '/places/$placeSlug',
  path: '/places/$placeSlug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFeedbackSlugRoute = PublicFeedbackSlugRouteImport.update({
  id: '/feedback/$slug',
  path: '/feedback/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEntriesEntryIdRoute = PublicEntriesEntryIdRouteImport.update({
  id: '/entries/$entryId',
  path: '/entries/$entryId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDirectoriesOrgIdRoute = PublicDirectoriesOrgIdRouteImport.update({
  id: '/directories/$orgId',
  path: '/directories/$orgId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicClaimSlugRoute = PublicClaimSlugRouteImport.update({
  id: '/claim/$slug',
  path: '/claim/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AuthStartCompleteRoute = AuthStartCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => AuthStartRoute,
} as any)
const AuthOauthConsentRoute = AuthOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeviceApprovedRoute = AuthDeviceApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => AuthDeviceRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthRoute,
  } as any)
const DotwellKnownOauthProtectedResourceMcpRoute =
  DotwellKnownOauthProtectedResourceMcpRouteImport.update({
    id: '/.well-known/oauth-protected-resource/mcp',
    path: '/.well-known/oauth-protected-resource/mcp',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicProfilesPeopleIndexRoute =
  PublicProfilesPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicProfilesPeopleRoute,
  } as any)
const PublicProfilesOrganizationsIndexRoute =
  PublicProfilesOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicProfilesOrganizationsRoute,
  } as any)
const ApiAuthInternalApiKeyRoute = ApiAuthInternalApiKeyRouteImport.update({
  id: '/api/auth/internal/api-key',
  path: '/api/auth/internal/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtprotoOauthStartRoute = ApiAtprotoOauthStartRouteImport.update({
  id: '/api/atproto/oauth/start',
  path: '/api/atproto/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtprotoOauthClientMetadataDotjsonRoute =
  ApiAtprotoOauthClientMetadataDotjsonRouteImport.update({
    id: '/api/atproto/oauth/client-metadata.json',
    path: '/api/atproto/oauth/client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAtprotoOauthCallbackRoute = ApiAtprotoOauthCallbackRouteImport.update({
  id: '/api/atproto/oauth/callback',
  path: '/api/atproto/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProfilesPeopleSlugRoute =
  PublicProfilesPeopleSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PublicProfilesPeopleRoute,
  } as any)
const PublicProfilesOrganizationsSlugRoute =
  PublicProfilesOrganizationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PublicProfilesOrganizationsRoute,
  } as any)
const PublicProfilesInitiativesSlugRoute =
  PublicProfilesInitiativesSlugRouteImport.update({
    id: '/profiles/initiatives/$slug',
    path: '/profiles/initiatives/$slug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicProfilesEventsSlugRoute =
  PublicProfilesEventsSlugRouteImport.update({
    id: '/profiles/events/$slug',
    path: '/profiles/events/$slug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicProfilesCampaignsSlugRoute =
  PublicProfilesCampaignsSlugRouteImport.update({
    id: '/profiles/campaigns/$slug',
    path: '/profiles/campaigns/$slug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesPolitiesPlaceSlugRoute =
  PublicPlacesPolitiesPlaceSlugRouteImport.update({
    id: '/places/polities/$placeSlug',
    path: '/places/polities/$placeSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesNeighborhoodsPlaceSlugRoute =
  PublicPlacesNeighborhoodsPlaceSlugRouteImport.update({
    id: '/places/neighborhoods/$placeSlug',
    path: '/places/neighborhoods/$placeSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesMetrosPlaceSlugRoute =
  PublicPlacesMetrosPlaceSlugRouteImport.update({
    id: '/places/metros/$placeSlug',
    path: '/places/metros/$placeSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesDistrictsPlaceSlugRoute =
  PublicPlacesDistrictsPlaceSlugRouteImport.update({
    id: '/places/districts/$placeSlug',
    path: '/places/districts/$placeSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesCountiesPlaceSlugRoute =
  PublicPlacesCountiesPlaceSlugRouteImport.update({
    id: '/places/counties/$placeSlug',
    path: '/places/counties/$placeSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesCitiesPlaceSlugRoute =
  PublicPlacesCitiesPlaceSlugRouteImport.update({
    id: '/places/cities/$placeSlug',
    path: '/places/cities/$placeSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPlacesBoroughsPlaceSlugRoute =
  PublicPlacesBoroughsPlaceSlugRouteImport.update({
    id: '/places/boroughs/$placeSlug',
    path: '/places/boroughs/$placeSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const DotwellKnownOauthAuthorizationServerApiAuthRoute =
  DotwellKnownOauthAuthorizationServerApiAuthRouteImport.update({
    id: '/.well-known/oauth-authorization-server/api/auth',
    path: '/.well-known/oauth-authorization-server/api/auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAtprotoOauthHarnessAuthorizeRoute =
  ApiAtprotoOauthHarnessAuthorizeRouteImport.update({
    id: '/api/atproto/oauth/harness/authorize',
    path: '/api/atproto/oauth/harness/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute =
  ApiAuthInternalMembershipsOrganizationIdMembersUserIdRouteImport.update({
    id: '/api/auth/internal/memberships/$organizationId/members/$userId',
    path: '/api/auth/internal/memberships/$organizationId/members/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/firehose.rss': typeof FirehoseDotrssRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/device': typeof AuthDeviceRouteWithChildren
  '/setup': typeof AuthSetupRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/start': typeof AuthStartRouteWithChildren
  '/browse': typeof PublicBrowseRoute
  '/firehose': typeof PublicFirehoseRoute
  '/map': typeof PublicMapRoute
  '/post-logout': typeof PublicPostLogoutRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/request-discount': typeof PublicRequestDiscountRoute
  '/security': typeof PublicSecurityRoute
  '/terms': typeof PublicTermsRoute
  '/account': typeof WorkspaceAccountRoute
  '/briefs': typeof WorkspaceBriefsRouteWithChildren
  '/checkout-complete': typeof WorkspaceCheckoutCompleteRoute
  '/coverage': typeof WorkspaceCoverageRouteWithChildren
  '/discovery': typeof WorkspaceDiscoveryRoute
  '/feed': typeof WorkspaceFeedRoute
  '/home': typeof WorkspaceHomeRoute
  '/lists': typeof WorkspaceListsRouteWithChildren
  '/organization': typeof WorkspaceOrganizationRouteWithChildren
  '/watching': typeof WorkspaceWatchingRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/device/approve': typeof DeviceApproveRoute
  '/device/code': typeof DeviceCodeRoute
  '/device/deny': typeof DeviceDenyRoute
  '/device/status': typeof DeviceStatusRoute
  '/device/token': typeof DeviceTokenRoute
  '/docs/$': typeof DocsSplatRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/device/approved': typeof AuthDeviceApprovedRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/start/complete': typeof AuthStartCompleteRoute
  '/claim/$slug': typeof PublicClaimSlugRoute
  '/directories/$orgId': typeof PublicDirectoriesOrgIdRoute
  '/entries/$entryId': typeof PublicEntriesEntryIdRoute
  '/feedback/$slug': typeof PublicFeedbackSlugRoute
  '/places/$placeSlug': typeof PublicPlacesPlaceSlugRoute
  '/profiles/organizations': typeof PublicProfilesOrganizationsRouteWithChildren
  '/profiles/people': typeof PublicProfilesPeopleRouteWithChildren
  '/admin/cloud-costs': typeof WorkspaceAdminCloudCostsRoute
  '/admin/discounts': typeof WorkspaceAdminDiscountsRoute
  '/admin/profile-claims': typeof WorkspaceAdminProfileClaimsRoute
  '/briefs/$briefId': typeof WorkspaceBriefsBriefIdRoute
  '/briefs/new': typeof WorkspaceBriefsNewRoute
  '/coverage/$targetId': typeof WorkspaceCoverageTargetIdRoute
  '/lists/$id': typeof WorkspaceListsIdRoute
  '/manage/$slug': typeof WorkspaceManageSlugRoute
  '/organization/sso': typeof WorkspaceOrganizationSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/.well-known/oauth-authorization-server/': typeof DotwellKnownOauthAuthorizationServerIndexRoute
  '/.well-known/oauth-protected-resource/': typeof DotwellKnownOauthProtectedResourceIndexRoute
  '/device/': typeof AuthDeviceIndexRoute
  '/profiles/': typeof PublicProfilesIndexRoute
  '/admin/': typeof WorkspaceAdminIndexRoute
  '/organization/': typeof WorkspaceOrganizationIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/places/boroughs/$placeSlug': typeof PublicPlacesBoroughsPlaceSlugRoute
  '/places/cities/$placeSlug': typeof PublicPlacesCitiesPlaceSlugRoute
  '/places/counties/$placeSlug': typeof PublicPlacesCountiesPlaceSlugRoute
  '/places/districts/$placeSlug': typeof PublicPlacesDistrictsPlaceSlugRoute
  '/places/metros/$placeSlug': typeof PublicPlacesMetrosPlaceSlugRoute
  '/places/neighborhoods/$placeSlug': typeof PublicPlacesNeighborhoodsPlaceSlugRoute
  '/places/polities/$placeSlug': typeof PublicPlacesPolitiesPlaceSlugRoute
  '/profiles/campaigns/$slug': typeof PublicProfilesCampaignsSlugRoute
  '/profiles/events/$slug': typeof PublicProfilesEventsSlugRoute
  '/profiles/initiatives/$slug': typeof PublicProfilesInitiativesSlugRoute
  '/profiles/organizations/$slug': typeof PublicProfilesOrganizationsSlugRoute
  '/profiles/people/$slug': typeof PublicProfilesPeopleSlugRoute
  '/api/atproto/oauth/callback': typeof ApiAtprotoOauthCallbackRoute
  '/api/atproto/oauth/client-metadata.json': typeof ApiAtprotoOauthClientMetadataDotjsonRoute
  '/api/atproto/oauth/start': typeof ApiAtprotoOauthStartRoute
  '/api/auth/internal/api-key': typeof ApiAuthInternalApiKeyRoute
  '/profiles/organizations/': typeof PublicProfilesOrganizationsIndexRoute
  '/profiles/people/': typeof PublicProfilesPeopleIndexRoute
  '/api/atproto/oauth/harness/authorize': typeof ApiAtprotoOauthHarnessAuthorizeRoute
  '/api/auth/internal/memberships/$organizationId/members/$userId': typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/firehose.rss': typeof FirehoseDotrssRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/setup': typeof AuthSetupRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/start': typeof AuthStartRouteWithChildren
  '/browse': typeof PublicBrowseRoute
  '/firehose': typeof PublicFirehoseRoute
  '/map': typeof PublicMapRoute
  '/post-logout': typeof PublicPostLogoutRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/request-discount': typeof PublicRequestDiscountRoute
  '/security': typeof PublicSecurityRoute
  '/terms': typeof PublicTermsRoute
  '/account': typeof WorkspaceAccountRoute
  '/briefs': typeof WorkspaceBriefsRouteWithChildren
  '/checkout-complete': typeof WorkspaceCheckoutCompleteRoute
  '/coverage': typeof WorkspaceCoverageRouteWithChildren
  '/discovery': typeof WorkspaceDiscoveryRoute
  '/feed': typeof WorkspaceFeedRoute
  '/home': typeof WorkspaceHomeRoute
  '/lists': typeof WorkspaceListsRouteWithChildren
  '/watching': typeof WorkspaceWatchingRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/device/approve': typeof DeviceApproveRoute
  '/device/code': typeof DeviceCodeRoute
  '/device/deny': typeof DeviceDenyRoute
  '/device/status': typeof DeviceStatusRoute
  '/device/token': typeof DeviceTokenRoute
  '/docs/$': typeof DocsSplatRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/device/approved': typeof AuthDeviceApprovedRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/start/complete': typeof AuthStartCompleteRoute
  '/claim/$slug': typeof PublicClaimSlugRoute
  '/directories/$orgId': typeof PublicDirectoriesOrgIdRoute
  '/entries/$entryId': typeof PublicEntriesEntryIdRoute
  '/feedback/$slug': typeof PublicFeedbackSlugRoute
  '/places/$placeSlug': typeof PublicPlacesPlaceSlugRoute
  '/admin/cloud-costs': typeof WorkspaceAdminCloudCostsRoute
  '/admin/discounts': typeof WorkspaceAdminDiscountsRoute
  '/admin/profile-claims': typeof WorkspaceAdminProfileClaimsRoute
  '/briefs/$briefId': typeof WorkspaceBriefsBriefIdRoute
  '/briefs/new': typeof WorkspaceBriefsNewRoute
  '/coverage/$targetId': typeof WorkspaceCoverageTargetIdRoute
  '/lists/$id': typeof WorkspaceListsIdRoute
  '/manage/$slug': typeof WorkspaceManageSlugRoute
  '/organization/sso': typeof WorkspaceOrganizationSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerIndexRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceIndexRoute
  '/device': typeof AuthDeviceIndexRoute
  '/profiles': typeof PublicProfilesIndexRoute
  '/admin': typeof WorkspaceAdminIndexRoute
  '/organization': typeof WorkspaceOrganizationIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/places/boroughs/$placeSlug': typeof PublicPlacesBoroughsPlaceSlugRoute
  '/places/cities/$placeSlug': typeof PublicPlacesCitiesPlaceSlugRoute
  '/places/counties/$placeSlug': typeof PublicPlacesCountiesPlaceSlugRoute
  '/places/districts/$placeSlug': typeof PublicPlacesDistrictsPlaceSlugRoute
  '/places/metros/$placeSlug': typeof PublicPlacesMetrosPlaceSlugRoute
  '/places/neighborhoods/$placeSlug': typeof PublicPlacesNeighborhoodsPlaceSlugRoute
  '/places/polities/$placeSlug': typeof PublicPlacesPolitiesPlaceSlugRoute
  '/profiles/campaigns/$slug': typeof PublicProfilesCampaignsSlugRoute
  '/profiles/events/$slug': typeof PublicProfilesEventsSlugRoute
  '/profiles/initiatives/$slug': typeof PublicProfilesInitiativesSlugRoute
  '/profiles/organizations/$slug': typeof PublicProfilesOrganizationsSlugRoute
  '/profiles/people/$slug': typeof PublicProfilesPeopleSlugRoute
  '/api/atproto/oauth/callback': typeof ApiAtprotoOauthCallbackRoute
  '/api/atproto/oauth/client-metadata.json': typeof ApiAtprotoOauthClientMetadataDotjsonRoute
  '/api/atproto/oauth/start': typeof ApiAtprotoOauthStartRoute
  '/api/auth/internal/api-key': typeof ApiAuthInternalApiKeyRoute
  '/profiles/organizations': typeof PublicProfilesOrganizationsIndexRoute
  '/profiles/people': typeof PublicProfilesPeopleIndexRoute
  '/api/atproto/oauth/harness/authorize': typeof ApiAtprotoOauthHarnessAuthorizeRoute
  '/api/auth/internal/memberships/$organizationId/members/$userId': typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/firehose.rss': typeof FirehoseDotrssRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/device': typeof AuthDeviceRouteWithChildren
  '/_auth/setup': typeof AuthSetupRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/start': typeof AuthStartRouteWithChildren
  '/_public/browse': typeof PublicBrowseRoute
  '/_public/firehose': typeof PublicFirehoseRoute
  '/_public/map': typeof PublicMapRoute
  '/_public/post-logout': typeof PublicPostLogoutRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/request-discount': typeof PublicRequestDiscountRoute
  '/_public/security': typeof PublicSecurityRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_workspace/account': typeof WorkspaceAccountRoute
  '/_workspace/briefs': typeof WorkspaceBriefsRouteWithChildren
  '/_workspace/checkout-complete': typeof WorkspaceCheckoutCompleteRoute
  '/_workspace/coverage': typeof WorkspaceCoverageRouteWithChildren
  '/_workspace/discovery': typeof WorkspaceDiscoveryRoute
  '/_workspace/feed': typeof WorkspaceFeedRoute
  '/_workspace/home': typeof WorkspaceHomeRoute
  '/_workspace/lists': typeof WorkspaceListsRouteWithChildren
  '/_workspace/organization': typeof WorkspaceOrganizationRouteWithChildren
  '/_workspace/watching': typeof WorkspaceWatchingRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/device/approve': typeof DeviceApproveRoute
  '/device/code': typeof DeviceCodeRoute
  '/device/deny': typeof DeviceDenyRoute
  '/device/status': typeof DeviceStatusRoute
  '/device/token': typeof DeviceTokenRoute
  '/docs/$': typeof DocsSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_auth/device/approved': typeof AuthDeviceApprovedRoute
  '/_auth/oauth/consent': typeof AuthOauthConsentRoute
  '/_auth/start/complete': typeof AuthStartCompleteRoute
  '/_public/claim/$slug': typeof PublicClaimSlugRoute
  '/_public/directories/$orgId': typeof PublicDirectoriesOrgIdRoute
  '/_public/entries/$entryId': typeof PublicEntriesEntryIdRoute
  '/_public/feedback/$slug': typeof PublicFeedbackSlugRoute
  '/_public/places/$placeSlug': typeof PublicPlacesPlaceSlugRoute
  '/_public/profiles/organizations': typeof PublicProfilesOrganizationsRouteWithChildren
  '/_public/profiles/people': typeof PublicProfilesPeopleRouteWithChildren
  '/_workspace/admin/cloud-costs': typeof WorkspaceAdminCloudCostsRoute
  '/_workspace/admin/discounts': typeof WorkspaceAdminDiscountsRoute
  '/_workspace/admin/profile-claims': typeof WorkspaceAdminProfileClaimsRoute
  '/_workspace/briefs/$briefId': typeof WorkspaceBriefsBriefIdRoute
  '/_workspace/briefs/new': typeof WorkspaceBriefsNewRoute
  '/_workspace/coverage/$targetId': typeof WorkspaceCoverageTargetIdRoute
  '/_workspace/lists/$id': typeof WorkspaceListsIdRoute
  '/_workspace/manage/$slug': typeof WorkspaceManageSlugRoute
  '/_workspace/organization/sso': typeof WorkspaceOrganizationSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/.well-known/oauth-authorization-server/': typeof DotwellKnownOauthAuthorizationServerIndexRoute
  '/.well-known/oauth-protected-resource/': typeof DotwellKnownOauthProtectedResourceIndexRoute
  '/_auth/device/': typeof AuthDeviceIndexRoute
  '/_public/profiles/': typeof PublicProfilesIndexRoute
  '/_workspace/admin/': typeof WorkspaceAdminIndexRoute
  '/_workspace/organization/': typeof WorkspaceOrganizationIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/_public/places/boroughs/$placeSlug': typeof PublicPlacesBoroughsPlaceSlugRoute
  '/_public/places/cities/$placeSlug': typeof PublicPlacesCitiesPlaceSlugRoute
  '/_public/places/counties/$placeSlug': typeof PublicPlacesCountiesPlaceSlugRoute
  '/_public/places/districts/$placeSlug': typeof PublicPlacesDistrictsPlaceSlugRoute
  '/_public/places/metros/$placeSlug': typeof PublicPlacesMetrosPlaceSlugRoute
  '/_public/places/neighborhoods/$placeSlug': typeof PublicPlacesNeighborhoodsPlaceSlugRoute
  '/_public/places/polities/$placeSlug': typeof PublicPlacesPolitiesPlaceSlugRoute
  '/_public/profiles/campaigns/$slug': typeof PublicProfilesCampaignsSlugRoute
  '/_public/profiles/events/$slug': typeof PublicProfilesEventsSlugRoute
  '/_public/profiles/initiatives/$slug': typeof PublicProfilesInitiativesSlugRoute
  '/_public/profiles/organizations/$slug': typeof PublicProfilesOrganizationsSlugRoute
  '/_public/profiles/people/$slug': typeof PublicProfilesPeopleSlugRoute
  '/api/atproto/oauth/callback': typeof ApiAtprotoOauthCallbackRoute
  '/api/atproto/oauth/client-metadata.json': typeof ApiAtprotoOauthClientMetadataDotjsonRoute
  '/api/atproto/oauth/start': typeof ApiAtprotoOauthStartRoute
  '/api/auth/internal/api-key': typeof ApiAuthInternalApiKeyRoute
  '/_public/profiles/organizations/': typeof PublicProfilesOrganizationsIndexRoute
  '/_public/profiles/people/': typeof PublicProfilesPeopleIndexRoute
  '/api/atproto/oauth/harness/authorize': typeof ApiAtprotoOauthHarnessAuthorizeRoute
  '/api/auth/internal/memberships/$organizationId/members/$userId': typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/firehose.rss'
    | '/health'
    | '/llms.txt'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/device'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/start'
    | '/browse'
    | '/firehose'
    | '/map'
    | '/post-logout'
    | '/pricing'
    | '/privacy'
    | '/request-discount'
    | '/security'
    | '/terms'
    | '/account'
    | '/briefs'
    | '/checkout-complete'
    | '/coverage'
    | '/discovery'
    | '/feed'
    | '/home'
    | '/lists'
    | '/organization'
    | '/watching'
    | '/api/$'
    | '/api/health'
    | '/device/approve'
    | '/device/code'
    | '/device/deny'
    | '/device/status'
    | '/device/token'
    | '/docs/$'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/accept-invitation/$invitationId'
    | '/device/approved'
    | '/oauth/consent'
    | '/start/complete'
    | '/claim/$slug'
    | '/directories/$orgId'
    | '/entries/$entryId'
    | '/feedback/$slug'
    | '/places/$placeSlug'
    | '/profiles/organizations'
    | '/profiles/people'
    | '/admin/cloud-costs'
    | '/admin/discounts'
    | '/admin/profile-claims'
    | '/briefs/$briefId'
    | '/briefs/new'
    | '/coverage/$targetId'
    | '/lists/$id'
    | '/manage/$slug'
    | '/organization/sso'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/.well-known/oauth-authorization-server/'
    | '/.well-known/oauth-protected-resource/'
    | '/device/'
    | '/profiles/'
    | '/admin/'
    | '/organization/'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/places/boroughs/$placeSlug'
    | '/places/cities/$placeSlug'
    | '/places/counties/$placeSlug'
    | '/places/districts/$placeSlug'
    | '/places/metros/$placeSlug'
    | '/places/neighborhoods/$placeSlug'
    | '/places/polities/$placeSlug'
    | '/profiles/campaigns/$slug'
    | '/profiles/events/$slug'
    | '/profiles/initiatives/$slug'
    | '/profiles/organizations/$slug'
    | '/profiles/people/$slug'
    | '/api/atproto/oauth/callback'
    | '/api/atproto/oauth/client-metadata.json'
    | '/api/atproto/oauth/start'
    | '/api/auth/internal/api-key'
    | '/profiles/organizations/'
    | '/profiles/people/'
    | '/api/atproto/oauth/harness/authorize'
    | '/api/auth/internal/memberships/$organizationId/members/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/firehose.rss'
    | '/health'
    | '/llms.txt'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/start'
    | '/browse'
    | '/firehose'
    | '/map'
    | '/post-logout'
    | '/pricing'
    | '/privacy'
    | '/request-discount'
    | '/security'
    | '/terms'
    | '/account'
    | '/briefs'
    | '/checkout-complete'
    | '/coverage'
    | '/discovery'
    | '/feed'
    | '/home'
    | '/lists'
    | '/watching'
    | '/api/$'
    | '/api/health'
    | '/device/approve'
    | '/device/code'
    | '/device/deny'
    | '/device/status'
    | '/device/token'
    | '/docs/$'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/accept-invitation/$invitationId'
    | '/device/approved'
    | '/oauth/consent'
    | '/start/complete'
    | '/claim/$slug'
    | '/directories/$orgId'
    | '/entries/$entryId'
    | '/feedback/$slug'
    | '/places/$placeSlug'
    | '/admin/cloud-costs'
    | '/admin/discounts'
    | '/admin/profile-claims'
    | '/briefs/$briefId'
    | '/briefs/new'
    | '/coverage/$targetId'
    | '/lists/$id'
    | '/manage/$slug'
    | '/organization/sso'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/device'
    | '/profiles'
    | '/admin'
    | '/organization'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/places/boroughs/$placeSlug'
    | '/places/cities/$placeSlug'
    | '/places/counties/$placeSlug'
    | '/places/districts/$placeSlug'
    | '/places/metros/$placeSlug'
    | '/places/neighborhoods/$placeSlug'
    | '/places/polities/$placeSlug'
    | '/profiles/campaigns/$slug'
    | '/profiles/events/$slug'
    | '/profiles/initiatives/$slug'
    | '/profiles/organizations/$slug'
    | '/profiles/people/$slug'
    | '/api/atproto/oauth/callback'
    | '/api/atproto/oauth/client-metadata.json'
    | '/api/atproto/oauth/start'
    | '/api/auth/internal/api-key'
    | '/profiles/organizations'
    | '/profiles/people'
    | '/api/atproto/oauth/harness/authorize'
    | '/api/auth/internal/memberships/$organizationId/members/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_workspace'
    | '/dashboard'
    | '/docs'
    | '/firehose.rss'
    | '/health'
    | '/llms.txt'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_auth/device'
    | '/_auth/setup'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/start'
    | '/_public/browse'
    | '/_public/firehose'
    | '/_public/map'
    | '/_public/post-logout'
    | '/_public/pricing'
    | '/_public/privacy'
    | '/_public/request-discount'
    | '/_public/security'
    | '/_public/terms'
    | '/_workspace/account'
    | '/_workspace/briefs'
    | '/_workspace/checkout-complete'
    | '/_workspace/coverage'
    | '/_workspace/discovery'
    | '/_workspace/feed'
    | '/_workspace/home'
    | '/_workspace/lists'
    | '/_workspace/organization'
    | '/_workspace/watching'
    | '/api/$'
    | '/api/health'
    | '/device/approve'
    | '/device/code'
    | '/device/deny'
    | '/device/status'
    | '/device/token'
    | '/docs/$'
    | '/_public/'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/_auth/accept-invitation/$invitationId'
    | '/_auth/device/approved'
    | '/_auth/oauth/consent'
    | '/_auth/start/complete'
    | '/_public/claim/$slug'
    | '/_public/directories/$orgId'
    | '/_public/entries/$entryId'
    | '/_public/feedback/$slug'
    | '/_public/places/$placeSlug'
    | '/_public/profiles/organizations'
    | '/_public/profiles/people'
    | '/_workspace/admin/cloud-costs'
    | '/_workspace/admin/discounts'
    | '/_workspace/admin/profile-claims'
    | '/_workspace/briefs/$briefId'
    | '/_workspace/briefs/new'
    | '/_workspace/coverage/$targetId'
    | '/_workspace/lists/$id'
    | '/_workspace/manage/$slug'
    | '/_workspace/organization/sso'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/.well-known/oauth-authorization-server/'
    | '/.well-known/oauth-protected-resource/'
    | '/_auth/device/'
    | '/_public/profiles/'
    | '/_workspace/admin/'
    | '/_workspace/organization/'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/_public/places/boroughs/$placeSlug'
    | '/_public/places/cities/$placeSlug'
    | '/_public/places/counties/$placeSlug'
    | '/_public/places/districts/$placeSlug'
    | '/_public/places/metros/$placeSlug'
    | '/_public/places/neighborhoods/$placeSlug'
    | '/_public/places/polities/$placeSlug'
    | '/_public/profiles/campaigns/$slug'
    | '/_public/profiles/events/$slug'
    | '/_public/profiles/initiatives/$slug'
    | '/_public/profiles/organizations/$slug'
    | '/_public/profiles/people/$slug'
    | '/api/atproto/oauth/callback'
    | '/api/atproto/oauth/client-metadata.json'
    | '/api/atproto/oauth/start'
    | '/api/auth/internal/api-key'
    | '/_public/profiles/organizations/'
    | '/_public/profiles/people/'
    | '/api/atproto/oauth/harness/authorize'
    | '/api/auth/internal/memberships/$organizationId/members/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRouteWithChildren
  FirehoseDotrssRoute: typeof FirehoseDotrssRoute
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceCodeRoute: typeof DeviceCodeRoute
  DeviceDenyRoute: typeof DeviceDenyRoute
  DeviceStatusRoute: typeof DeviceStatusRoute
  DeviceTokenRoute: typeof DeviceTokenRoute
  DotwellKnownOauthProtectedResourceMcpRoute: typeof DotwellKnownOauthProtectedResourceMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  DotwellKnownOauthAuthorizationServerIndexRoute: typeof DotwellKnownOauthAuthorizationServerIndexRoute
  DotwellKnownOauthProtectedResourceIndexRoute: typeof DotwellKnownOauthProtectedResourceIndexRoute
  DotwellKnownOauthAuthorizationServerApiAuthRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  ApiAtprotoOauthCallbackRoute: typeof ApiAtprotoOauthCallbackRoute
  ApiAtprotoOauthClientMetadataDotjsonRoute: typeof ApiAtprotoOauthClientMetadataDotjsonRoute
  ApiAtprotoOauthStartRoute: typeof ApiAtprotoOauthStartRoute
  ApiAuthInternalApiKeyRoute: typeof ApiAuthInternalApiKeyRoute
  ApiAtprotoOauthHarnessAuthorizeRoute: typeof ApiAtprotoOauthHarnessAuthorizeRoute
  ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute: typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firehose.rss': {
      id: '/firehose.rss'
      path: '/firehose.rss'
      fullPath: '/firehose.rss'
      preLoaderRoute: typeof FirehoseDotrssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/device/token': {
      id: '/device/token'
      path: '/device/token'
      fullPath: '/device/token'
      preLoaderRoute: typeof DeviceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/status': {
      id: '/device/status'
      path: '/device/status'
      fullPath: '/device/status'
      preLoaderRoute: typeof DeviceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/deny': {
      id: '/device/deny'
      path: '/device/deny'
      fullPath: '/device/deny'
      preLoaderRoute: typeof DeviceDenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/code': {
      id: '/device/code'
      path: '/device/code'
      fullPath: '/device/code'
      preLoaderRoute: typeof DeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/device/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/watching': {
      id: '/_workspace/watching'
      path: '/watching'
      fullPath: '/watching'
      preLoaderRoute: typeof WorkspaceWatchingRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/organization': {
      id: '/_workspace/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof WorkspaceOrganizationRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/lists': {
      id: '/_workspace/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof WorkspaceListsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/home': {
      id: '/_workspace/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof WorkspaceHomeRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/feed': {
      id: '/_workspace/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof WorkspaceFeedRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/discovery': {
      id: '/_workspace/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof WorkspaceDiscoveryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/coverage': {
      id: '/_workspace/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof WorkspaceCoverageRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/checkout-complete': {
      id: '/_workspace/checkout-complete'
      path: '/checkout-complete'
      fullPath: '/checkout-complete'
      preLoaderRoute: typeof WorkspaceCheckoutCompleteRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/briefs': {
      id: '/_workspace/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof WorkspaceBriefsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/account': {
      id: '/_workspace/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WorkspaceAccountRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/security': {
      id: '/_public/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof PublicSecurityRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/request-discount': {
      id: '/_public/request-discount'
      path: '/request-discount'
      fullPath: '/request-discount'
      preLoaderRoute: typeof PublicRequestDiscountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/post-logout': {
      id: '/_public/post-logout'
      path: '/post-logout'
      fullPath: '/post-logout'
      preLoaderRoute: typeof PublicPostLogoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/map': {
      id: '/_public/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof PublicMapRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/firehose': {
      id: '/_public/firehose'
      path: '/firehose'
      fullPath: '/firehose'
      preLoaderRoute: typeof PublicFirehoseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/browse': {
      id: '/_public/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof PublicBrowseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/start': {
      id: '/_auth/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/device': {
      id: '/_auth/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_workspace/organization/': {
      id: '/_workspace/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof WorkspaceOrganizationIndexRouteImport
      parentRoute: typeof WorkspaceOrganizationRoute
    }
    '/_workspace/admin/': {
      id: '/_workspace/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof WorkspaceAdminIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/profiles/': {
      id: '/_public/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof PublicProfilesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/device/': {
      id: '/_auth/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof AuthDeviceIndexRouteImport
      parentRoute: typeof AuthDeviceRoute
    }
    '/.well-known/oauth-protected-resource/': {
      id: '/.well-known/oauth-protected-resource/'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource/'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/': {
      id: '/.well-known/oauth-authorization-server/'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server/'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/organization/sso': {
      id: '/_workspace/organization/sso'
      path: '/sso'
      fullPath: '/organization/sso'
      preLoaderRoute: typeof WorkspaceOrganizationSsoRouteImport
      parentRoute: typeof WorkspaceOrganizationRoute
    }
    '/_workspace/manage/$slug': {
      id: '/_workspace/manage/$slug'
      path: '/manage/$slug'
      fullPath: '/manage/$slug'
      preLoaderRoute: typeof WorkspaceManageSlugRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/lists/$id': {
      id: '/_workspace/lists/$id'
      path: '/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof WorkspaceListsIdRouteImport
      parentRoute: typeof WorkspaceListsRoute
    }
    '/_workspace/coverage/$targetId': {
      id: '/_workspace/coverage/$targetId'
      path: '/$targetId'
      fullPath: '/coverage/$targetId'
      preLoaderRoute: typeof WorkspaceCoverageTargetIdRouteImport
      parentRoute: typeof WorkspaceCoverageRoute
    }
    '/_workspace/briefs/new': {
      id: '/_workspace/briefs/new'
      path: '/new'
      fullPath: '/briefs/new'
      preLoaderRoute: typeof WorkspaceBriefsNewRouteImport
      parentRoute: typeof WorkspaceBriefsRoute
    }
    '/_workspace/briefs/$briefId': {
      id: '/_workspace/briefs/$briefId'
      path: '/$briefId'
      fullPath: '/briefs/$briefId'
      preLoaderRoute: typeof WorkspaceBriefsBriefIdRouteImport
      parentRoute: typeof WorkspaceBriefsRoute
    }
    '/_workspace/admin/profile-claims': {
      id: '/_workspace/admin/profile-claims'
      path: '/admin/profile-claims'
      fullPath: '/admin/profile-claims'
      preLoaderRoute: typeof WorkspaceAdminProfileClaimsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/admin/discounts': {
      id: '/_workspace/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof WorkspaceAdminDiscountsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/admin/cloud-costs': {
      id: '/_workspace/admin/cloud-costs'
      path: '/admin/cloud-costs'
      fullPath: '/admin/cloud-costs'
      preLoaderRoute: typeof WorkspaceAdminCloudCostsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/profiles/people': {
      id: '/_public/profiles/people'
      path: '/profiles/people'
      fullPath: '/profiles/people'
      preLoaderRoute: typeof PublicProfilesPeopleRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/profiles/organizations': {
      id: '/_public/profiles/organizations'
      path: '/profiles/organizations'
      fullPath: '/profiles/organizations'
      preLoaderRoute: typeof PublicProfilesOrganizationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/$placeSlug': {
      id: '/_public/places/$placeSlug'
      path: '/places/$placeSlug'
      fullPath: '/places/$placeSlug'
      preLoaderRoute: typeof PublicPlacesPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/feedback/$slug': {
      id: '/_public/feedback/$slug'
      path: '/feedback/$slug'
      fullPath: '/feedback/$slug'
      preLoaderRoute: typeof PublicFeedbackSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/entries/$entryId': {
      id: '/_public/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof PublicEntriesEntryIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/directories/$orgId': {
      id: '/_public/directories/$orgId'
      path: '/directories/$orgId'
      fullPath: '/directories/$orgId'
      preLoaderRoute: typeof PublicDirectoriesOrgIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/claim/$slug': {
      id: '/_public/claim/$slug'
      path: '/claim/$slug'
      fullPath: '/claim/$slug'
      preLoaderRoute: typeof PublicClaimSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/start/complete': {
      id: '/_auth/start/complete'
      path: '/complete'
      fullPath: '/start/complete'
      preLoaderRoute: typeof AuthStartCompleteRouteImport
      parentRoute: typeof AuthStartRoute
    }
    '/_auth/oauth/consent': {
      id: '/_auth/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AuthOauthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/device/approved': {
      id: '/_auth/device/approved'
      path: '/approved'
      fullPath: '/device/approved'
      preLoaderRoute: typeof AuthDeviceApprovedRouteImport
      parentRoute: typeof AuthDeviceRoute
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/.well-known/oauth-protected-resource/mcp': {
      id: '/.well-known/oauth-protected-resource/mcp'
      path: '/.well-known/oauth-protected-resource/mcp'
      fullPath: '/.well-known/oauth-protected-resource/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/profiles/people/': {
      id: '/_public/profiles/people/'
      path: '/'
      fullPath: '/profiles/people/'
      preLoaderRoute: typeof PublicProfilesPeopleIndexRouteImport
      parentRoute: typeof PublicProfilesPeopleRoute
    }
    '/_public/profiles/organizations/': {
      id: '/_public/profiles/organizations/'
      path: '/'
      fullPath: '/profiles/organizations/'
      preLoaderRoute: typeof PublicProfilesOrganizationsIndexRouteImport
      parentRoute: typeof PublicProfilesOrganizationsRoute
    }
    '/api/auth/internal/api-key': {
      id: '/api/auth/internal/api-key'
      path: '/api/auth/internal/api-key'
      fullPath: '/api/auth/internal/api-key'
      preLoaderRoute: typeof ApiAuthInternalApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atproto/oauth/start': {
      id: '/api/atproto/oauth/start'
      path: '/api/atproto/oauth/start'
      fullPath: '/api/atproto/oauth/start'
      preLoaderRoute: typeof ApiAtprotoOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atproto/oauth/client-metadata.json': {
      id: '/api/atproto/oauth/client-metadata.json'
      path: '/api/atproto/oauth/client-metadata.json'
      fullPath: '/api/atproto/oauth/client-metadata.json'
      preLoaderRoute: typeof ApiAtprotoOauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atproto/oauth/callback': {
      id: '/api/atproto/oauth/callback'
      path: '/api/atproto/oauth/callback'
      fullPath: '/api/atproto/oauth/callback'
      preLoaderRoute: typeof ApiAtprotoOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/profiles/people/$slug': {
      id: '/_public/profiles/people/$slug'
      path: '/$slug'
      fullPath: '/profiles/people/$slug'
      preLoaderRoute: typeof PublicProfilesPeopleSlugRouteImport
      parentRoute: typeof PublicProfilesPeopleRoute
    }
    '/_public/profiles/organizations/$slug': {
      id: '/_public/profiles/organizations/$slug'
      path: '/$slug'
      fullPath: '/profiles/organizations/$slug'
      preLoaderRoute: typeof PublicProfilesOrganizationsSlugRouteImport
      parentRoute: typeof PublicProfilesOrganizationsRoute
    }
    '/_public/profiles/initiatives/$slug': {
      id: '/_public/profiles/initiatives/$slug'
      path: '/profiles/initiatives/$slug'
      fullPath: '/profiles/initiatives/$slug'
      preLoaderRoute: typeof PublicProfilesInitiativesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/profiles/events/$slug': {
      id: '/_public/profiles/events/$slug'
      path: '/profiles/events/$slug'
      fullPath: '/profiles/events/$slug'
      preLoaderRoute: typeof PublicProfilesEventsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/profiles/campaigns/$slug': {
      id: '/_public/profiles/campaigns/$slug'
      path: '/profiles/campaigns/$slug'
      fullPath: '/profiles/campaigns/$slug'
      preLoaderRoute: typeof PublicProfilesCampaignsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/polities/$placeSlug': {
      id: '/_public/places/polities/$placeSlug'
      path: '/places/polities/$placeSlug'
      fullPath: '/places/polities/$placeSlug'
      preLoaderRoute: typeof PublicPlacesPolitiesPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/neighborhoods/$placeSlug': {
      id: '/_public/places/neighborhoods/$placeSlug'
      path: '/places/neighborhoods/$placeSlug'
      fullPath: '/places/neighborhoods/$placeSlug'
      preLoaderRoute: typeof PublicPlacesNeighborhoodsPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/metros/$placeSlug': {
      id: '/_public/places/metros/$placeSlug'
      path: '/places/metros/$placeSlug'
      fullPath: '/places/metros/$placeSlug'
      preLoaderRoute: typeof PublicPlacesMetrosPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/districts/$placeSlug': {
      id: '/_public/places/districts/$placeSlug'
      path: '/places/districts/$placeSlug'
      fullPath: '/places/districts/$placeSlug'
      preLoaderRoute: typeof PublicPlacesDistrictsPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/counties/$placeSlug': {
      id: '/_public/places/counties/$placeSlug'
      path: '/places/counties/$placeSlug'
      fullPath: '/places/counties/$placeSlug'
      preLoaderRoute: typeof PublicPlacesCountiesPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/cities/$placeSlug': {
      id: '/_public/places/cities/$placeSlug'
      path: '/places/cities/$placeSlug'
      fullPath: '/places/cities/$placeSlug'
      preLoaderRoute: typeof PublicPlacesCitiesPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/places/boroughs/$placeSlug': {
      id: '/_public/places/boroughs/$placeSlug'
      path: '/places/boroughs/$placeSlug'
      fullPath: '/places/boroughs/$placeSlug'
      preLoaderRoute: typeof PublicPlacesBoroughsPlaceSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/.well-known/oauth-authorization-server/api/auth': {
      id: '/.well-known/oauth-authorization-server/api/auth'
      path: '/.well-known/oauth-authorization-server/api/auth'
      fullPath: '/.well-known/oauth-authorization-server/api/auth'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atproto/oauth/harness/authorize': {
      id: '/api/atproto/oauth/harness/authorize'
      path: '/api/atproto/oauth/harness/authorize'
      fullPath: '/api/atproto/oauth/harness/authorize'
      preLoaderRoute: typeof ApiAtprotoOauthHarnessAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/internal/memberships/$organizationId/members/$userId': {
      id: '/api/auth/internal/memberships/$organizationId/members/$userId'
      path: '/api/auth/internal/memberships/$organizationId/members/$userId'
      fullPath: '/api/auth/internal/memberships/$organizationId/members/$userId'
      preLoaderRoute: typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthDeviceRouteChildren {
  AuthDeviceApprovedRoute: typeof AuthDeviceApprovedRoute
  AuthDeviceIndexRoute: typeof AuthDeviceIndexRoute
}

const AuthDeviceRouteChildren: AuthDeviceRouteChildren = {
  AuthDeviceApprovedRoute: AuthDeviceApprovedRoute,
  AuthDeviceIndexRoute: AuthDeviceIndexRoute,
}

const AuthDeviceRouteWithChildren = AuthDeviceRoute._addFileChildren(
  AuthDeviceRouteChildren,
)

interface AuthStartRouteChildren {
  AuthStartCompleteRoute: typeof AuthStartCompleteRoute
}

const AuthStartRouteChildren: AuthStartRouteChildren = {
  AuthStartCompleteRoute: AuthStartCompleteRoute,
}

const AuthStartRouteWithChildren = AuthStartRoute._addFileChildren(
  AuthStartRouteChildren,
)

interface AuthRouteChildren {
  AuthDeviceRoute: typeof AuthDeviceRouteWithChildren
  AuthSetupRoute: typeof AuthSetupRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthStartRoute: typeof AuthStartRouteWithChildren
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
  AuthOauthConsentRoute: typeof AuthOauthConsentRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDeviceRoute: AuthDeviceRouteWithChildren,
  AuthSetupRoute: AuthSetupRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthStartRoute: AuthStartRouteWithChildren,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
  AuthOauthConsentRoute: AuthOauthConsentRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicProfilesOrganizationsRouteChildren {
  PublicProfilesOrganizationsSlugRoute: typeof PublicProfilesOrganizationsSlugRoute
  PublicProfilesOrganizationsIndexRoute: typeof PublicProfilesOrganizationsIndexRoute
}

const PublicProfilesOrganizationsRouteChildren: PublicProfilesOrganizationsRouteChildren =
  {
    PublicProfilesOrganizationsSlugRoute: PublicProfilesOrganizationsSlugRoute,
    PublicProfilesOrganizationsIndexRoute:
      PublicProfilesOrganizationsIndexRoute,
  }

const PublicProfilesOrganizationsRouteWithChildren =
  PublicProfilesOrganizationsRoute._addFileChildren(
    PublicProfilesOrganizationsRouteChildren,
  )

interface PublicProfilesPeopleRouteChildren {
  PublicProfilesPeopleSlugRoute: typeof PublicProfilesPeopleSlugRoute
  PublicProfilesPeopleIndexRoute: typeof PublicProfilesPeopleIndexRoute
}

const PublicProfilesPeopleRouteChildren: PublicProfilesPeopleRouteChildren = {
  PublicProfilesPeopleSlugRoute: PublicProfilesPeopleSlugRoute,
  PublicProfilesPeopleIndexRoute: PublicProfilesPeopleIndexRoute,
}

const PublicProfilesPeopleRouteWithChildren =
  PublicProfilesPeopleRoute._addFileChildren(PublicProfilesPeopleRouteChildren)

interface PublicRouteChildren {
  PublicBrowseRoute: typeof PublicBrowseRoute
  PublicFirehoseRoute: typeof PublicFirehoseRoute
  PublicMapRoute: typeof PublicMapRoute
  PublicPostLogoutRoute: typeof PublicPostLogoutRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRequestDiscountRoute: typeof PublicRequestDiscountRoute
  PublicSecurityRoute: typeof PublicSecurityRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicClaimSlugRoute: typeof PublicClaimSlugRoute
  PublicDirectoriesOrgIdRoute: typeof PublicDirectoriesOrgIdRoute
  PublicEntriesEntryIdRoute: typeof PublicEntriesEntryIdRoute
  PublicFeedbackSlugRoute: typeof PublicFeedbackSlugRoute
  PublicPlacesPlaceSlugRoute: typeof PublicPlacesPlaceSlugRoute
  PublicProfilesOrganizationsRoute: typeof PublicProfilesOrganizationsRouteWithChildren
  PublicProfilesPeopleRoute: typeof PublicProfilesPeopleRouteWithChildren
  PublicProfilesIndexRoute: typeof PublicProfilesIndexRoute
  PublicPlacesBoroughsPlaceSlugRoute: typeof PublicPlacesBoroughsPlaceSlugRoute
  PublicPlacesCitiesPlaceSlugRoute: typeof PublicPlacesCitiesPlaceSlugRoute
  PublicPlacesCountiesPlaceSlugRoute: typeof PublicPlacesCountiesPlaceSlugRoute
  PublicPlacesDistrictsPlaceSlugRoute: typeof PublicPlacesDistrictsPlaceSlugRoute
  PublicPlacesMetrosPlaceSlugRoute: typeof PublicPlacesMetrosPlaceSlugRoute
  PublicPlacesNeighborhoodsPlaceSlugRoute: typeof PublicPlacesNeighborhoodsPlaceSlugRoute
  PublicPlacesPolitiesPlaceSlugRoute: typeof PublicPlacesPolitiesPlaceSlugRoute
  PublicProfilesCampaignsSlugRoute: typeof PublicProfilesCampaignsSlugRoute
  PublicProfilesEventsSlugRoute: typeof PublicProfilesEventsSlugRoute
  PublicProfilesInitiativesSlugRoute: typeof PublicProfilesInitiativesSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBrowseRoute: PublicBrowseRoute,
  PublicFirehoseRoute: PublicFirehoseRoute,
  PublicMapRoute: PublicMapRoute,
  PublicPostLogoutRoute: PublicPostLogoutRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRequestDiscountRoute: PublicRequestDiscountRoute,
  PublicSecurityRoute: PublicSecurityRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicClaimSlugRoute: PublicClaimSlugRoute,
  PublicDirectoriesOrgIdRoute: PublicDirectoriesOrgIdRoute,
  PublicEntriesEntryIdRoute: PublicEntriesEntryIdRoute,
  PublicFeedbackSlugRoute: PublicFeedbackSlugRoute,
  PublicPlacesPlaceSlugRoute: PublicPlacesPlaceSlugRoute,
  PublicProfilesOrganizationsRoute:
    PublicProfilesOrganizationsRouteWithChildren,
  PublicProfilesPeopleRoute: PublicProfilesPeopleRouteWithChildren,
  PublicProfilesIndexRoute: PublicProfilesIndexRoute,
  PublicPlacesBoroughsPlaceSlugRoute: PublicPlacesBoroughsPlaceSlugRoute,
  PublicPlacesCitiesPlaceSlugRoute: PublicPlacesCitiesPlaceSlugRoute,
  PublicPlacesCountiesPlaceSlugRoute: PublicPlacesCountiesPlaceSlugRoute,
  PublicPlacesDistrictsPlaceSlugRoute: PublicPlacesDistrictsPlaceSlugRoute,
  PublicPlacesMetrosPlaceSlugRoute: PublicPlacesMetrosPlaceSlugRoute,
  PublicPlacesNeighborhoodsPlaceSlugRoute:
    PublicPlacesNeighborhoodsPlaceSlugRoute,
  PublicPlacesPolitiesPlaceSlugRoute: PublicPlacesPolitiesPlaceSlugRoute,
  PublicProfilesCampaignsSlugRoute: PublicProfilesCampaignsSlugRoute,
  PublicProfilesEventsSlugRoute: PublicProfilesEventsSlugRoute,
  PublicProfilesInitiativesSlugRoute: PublicProfilesInitiativesSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface WorkspaceBriefsRouteChildren {
  WorkspaceBriefsBriefIdRoute: typeof WorkspaceBriefsBriefIdRoute
  WorkspaceBriefsNewRoute: typeof WorkspaceBriefsNewRoute
}

const WorkspaceBriefsRouteChildren: WorkspaceBriefsRouteChildren = {
  WorkspaceBriefsBriefIdRoute: WorkspaceBriefsBriefIdRoute,
  WorkspaceBriefsNewRoute: WorkspaceBriefsNewRoute,
}

const WorkspaceBriefsRouteWithChildren = WorkspaceBriefsRoute._addFileChildren(
  WorkspaceBriefsRouteChildren,
)

interface WorkspaceCoverageRouteChildren {
  WorkspaceCoverageTargetIdRoute: typeof WorkspaceCoverageTargetIdRoute
}

const WorkspaceCoverageRouteChildren: WorkspaceCoverageRouteChildren = {
  WorkspaceCoverageTargetIdRoute: WorkspaceCoverageTargetIdRoute,
}

const WorkspaceCoverageRouteWithChildren =
  WorkspaceCoverageRoute._addFileChildren(WorkspaceCoverageRouteChildren)

interface WorkspaceListsRouteChildren {
  WorkspaceListsIdRoute: typeof WorkspaceListsIdRoute
}

const WorkspaceListsRouteChildren: WorkspaceListsRouteChildren = {
  WorkspaceListsIdRoute: WorkspaceListsIdRoute,
}

const WorkspaceListsRouteWithChildren = WorkspaceListsRoute._addFileChildren(
  WorkspaceListsRouteChildren,
)

interface WorkspaceOrganizationRouteChildren {
  WorkspaceOrganizationSsoRoute: typeof WorkspaceOrganizationSsoRoute
  WorkspaceOrganizationIndexRoute: typeof WorkspaceOrganizationIndexRoute
}

const WorkspaceOrganizationRouteChildren: WorkspaceOrganizationRouteChildren = {
  WorkspaceOrganizationSsoRoute: WorkspaceOrganizationSsoRoute,
  WorkspaceOrganizationIndexRoute: WorkspaceOrganizationIndexRoute,
}

const WorkspaceOrganizationRouteWithChildren =
  WorkspaceOrganizationRoute._addFileChildren(
    WorkspaceOrganizationRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceAccountRoute: typeof WorkspaceAccountRoute
  WorkspaceBriefsRoute: typeof WorkspaceBriefsRouteWithChildren
  WorkspaceCheckoutCompleteRoute: typeof WorkspaceCheckoutCompleteRoute
  WorkspaceCoverageRoute: typeof WorkspaceCoverageRouteWithChildren
  WorkspaceDiscoveryRoute: typeof WorkspaceDiscoveryRoute
  WorkspaceFeedRoute: typeof WorkspaceFeedRoute
  WorkspaceHomeRoute: typeof WorkspaceHomeRoute
  WorkspaceListsRoute: typeof WorkspaceListsRouteWithChildren
  WorkspaceOrganizationRoute: typeof WorkspaceOrganizationRouteWithChildren
  WorkspaceWatchingRoute: typeof WorkspaceWatchingRoute
  WorkspaceAdminCloudCostsRoute: typeof WorkspaceAdminCloudCostsRoute
  WorkspaceAdminDiscountsRoute: typeof WorkspaceAdminDiscountsRoute
  WorkspaceAdminProfileClaimsRoute: typeof WorkspaceAdminProfileClaimsRoute
  WorkspaceManageSlugRoute: typeof WorkspaceManageSlugRoute
  WorkspaceAdminIndexRoute: typeof WorkspaceAdminIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAccountRoute: WorkspaceAccountRoute,
  WorkspaceBriefsRoute: WorkspaceBriefsRouteWithChildren,
  WorkspaceCheckoutCompleteRoute: WorkspaceCheckoutCompleteRoute,
  WorkspaceCoverageRoute: WorkspaceCoverageRouteWithChildren,
  WorkspaceDiscoveryRoute: WorkspaceDiscoveryRoute,
  WorkspaceFeedRoute: WorkspaceFeedRoute,
  WorkspaceHomeRoute: WorkspaceHomeRoute,
  WorkspaceListsRoute: WorkspaceListsRouteWithChildren,
  WorkspaceOrganizationRoute: WorkspaceOrganizationRouteWithChildren,
  WorkspaceWatchingRoute: WorkspaceWatchingRoute,
  WorkspaceAdminCloudCostsRoute: WorkspaceAdminCloudCostsRoute,
  WorkspaceAdminDiscountsRoute: WorkspaceAdminDiscountsRoute,
  WorkspaceAdminProfileClaimsRoute: WorkspaceAdminProfileClaimsRoute,
  WorkspaceManageSlugRoute: WorkspaceManageSlugRoute,
  WorkspaceAdminIndexRoute: WorkspaceAdminIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRouteWithChildren,
  FirehoseDotrssRoute: FirehoseDotrssRoute,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceCodeRoute: DeviceCodeRoute,
  DeviceDenyRoute: DeviceDenyRoute,
  DeviceStatusRoute: DeviceStatusRoute,
  DeviceTokenRoute: DeviceTokenRoute,
  DotwellKnownOauthProtectedResourceMcpRoute:
    DotwellKnownOauthProtectedResourceMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  DotwellKnownOauthAuthorizationServerIndexRoute:
    DotwellKnownOauthAuthorizationServerIndexRoute,
  DotwellKnownOauthProtectedResourceIndexRoute:
    DotwellKnownOauthProtectedResourceIndexRoute,
  DotwellKnownOauthAuthorizationServerApiAuthRoute:
    DotwellKnownOauthAuthorizationServerApiAuthRoute,
  ApiAtprotoOauthCallbackRoute: ApiAtprotoOauthCallbackRoute,
  ApiAtprotoOauthClientMetadataDotjsonRoute:
    ApiAtprotoOauthClientMetadataDotjsonRoute,
  ApiAtprotoOauthStartRoute: ApiAtprotoOauthStartRoute,
  ApiAuthInternalApiKeyRoute: ApiAuthInternalApiKeyRoute,
  ApiAtprotoOauthHarnessAuthorizeRoute: ApiAtprotoOauthHarnessAuthorizeRoute,
  ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute:
    ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
