/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as WorkspaceOrganizationRouteImport } from './routes/_workspace/organization'
import { Route as WorkspaceDiscoveryRouteImport } from './routes/_workspace/discovery'
import { Route as WorkspaceAccountRouteImport } from './routes/_workspace/account'
import { Route as PublicRequestDiscountRouteImport } from './routes/_public/request-discount'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicBrowseRouteImport } from './routes/_public/browse'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthAccountSetupRouteImport } from './routes/_auth/account-setup'
import { Route as WorkspaceOrganizationIndexRouteImport } from './routes/_workspace/organization.index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceOrganizationSsoRouteImport } from './routes/_workspace/organization.sso'
import { Route as WorkspaceAdminDiscountsRouteImport } from './routes/_workspace/admin.discounts'
import { Route as PublicEntriesEntryIdRouteImport } from './routes/_public/entries.$entryId'
import { Route as AuthOauthConsentRouteImport } from './routes/_auth/oauth/consent'
import { Route as ApiAuthInternalApiKeyRouteImport } from './routes/api/auth/internal/api-key'
import { Route as PublicProfilesPeopleSlugRouteImport } from './routes/_public/profiles/people.$slug'
import { Route as PublicProfilesOrganizationsSlugRouteImport } from './routes/_public/profiles/organizations.$slug'
import { Route as ApiAuthInternalMembershipsOrganizationIdMembersUserIdRouteImport } from './routes/api/auth/internal/memberships.$organizationId.members.$userId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceOrganizationRoute = WorkspaceOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDiscoveryRoute = WorkspaceDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAccountRoute = WorkspaceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicRequestDiscountRoute = PublicRequestDiscountRouteImport.update({
  id: '/request-discount',
  path: '/request-discount',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBrowseRoute = PublicBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => PublicRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountSetupRoute = AuthAccountSetupRouteImport.update({
  id: '/account-setup',
  path: '/account-setup',
  getParentRoute: () => AuthRoute,
} as any)
const WorkspaceOrganizationIndexRoute =
  WorkspaceOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceOrganizationRoute,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceOrganizationSsoRoute =
  WorkspaceOrganizationSsoRouteImport.update({
    id: '/sso',
    path: '/sso',
    getParentRoute: () => WorkspaceOrganizationRoute,
  } as any)
const WorkspaceAdminDiscountsRoute = WorkspaceAdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicEntriesEntryIdRoute = PublicEntriesEntryIdRouteImport.update({
  id: '/entries/$entryId',
  path: '/entries/$entryId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthOauthConsentRoute = AuthOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthInternalApiKeyRoute = ApiAuthInternalApiKeyRouteImport.update({
  id: '/api/auth/internal/api-key',
  path: '/api/auth/internal/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProfilesPeopleSlugRoute =
  PublicProfilesPeopleSlugRouteImport.update({
    id: '/profiles/people/$slug',
    path: '/profiles/people/$slug',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicProfilesOrganizationsSlugRoute =
  PublicProfilesOrganizationsSlugRouteImport.update({
    id: '/profiles/organizations/$slug',
    path: '/profiles/organizations/$slug',
    getParentRoute: () => PublicRoute,
  } as any)
const ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute =
  ApiAuthInternalMembershipsOrganizationIdMembersUserIdRouteImport.update({
    id: '/api/auth/internal/memberships/$organizationId/members/$userId',
    path: '/api/auth/internal/memberships/$organizationId/members/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account-setup': typeof AuthAccountSetupRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/browse': typeof PublicBrowseRoute
  '/pricing': typeof PublicPricingRoute
  '/request-discount': typeof PublicRequestDiscountRoute
  '/account': typeof WorkspaceAccountRoute
  '/discovery': typeof WorkspaceDiscoveryRoute
  '/organization': typeof WorkspaceOrganizationRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/entries/$entryId': typeof PublicEntriesEntryIdRoute
  '/admin/discounts': typeof WorkspaceAdminDiscountsRoute
  '/organization/sso': typeof WorkspaceOrganizationSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/organization/': typeof WorkspaceOrganizationIndexRoute
  '/profiles/organizations/$slug': typeof PublicProfilesOrganizationsSlugRoute
  '/profiles/people/$slug': typeof PublicProfilesPeopleSlugRoute
  '/api/auth/internal/api-key': typeof ApiAuthInternalApiKeyRoute
  '/api/auth/internal/memberships/$organizationId/members/$userId': typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account-setup': typeof AuthAccountSetupRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/browse': typeof PublicBrowseRoute
  '/pricing': typeof PublicPricingRoute
  '/request-discount': typeof PublicRequestDiscountRoute
  '/account': typeof WorkspaceAccountRoute
  '/discovery': typeof WorkspaceDiscoveryRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/entries/$entryId': typeof PublicEntriesEntryIdRoute
  '/admin/discounts': typeof WorkspaceAdminDiscountsRoute
  '/organization/sso': typeof WorkspaceOrganizationSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/organization': typeof WorkspaceOrganizationIndexRoute
  '/profiles/organizations/$slug': typeof PublicProfilesOrganizationsSlugRoute
  '/profiles/people/$slug': typeof PublicProfilesPeopleSlugRoute
  '/api/auth/internal/api-key': typeof ApiAuthInternalApiKeyRoute
  '/api/auth/internal/memberships/$organizationId/members/$userId': typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/account-setup': typeof AuthAccountSetupRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_public/browse': typeof PublicBrowseRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/request-discount': typeof PublicRequestDiscountRoute
  '/_workspace/account': typeof WorkspaceAccountRoute
  '/_workspace/discovery': typeof WorkspaceDiscoveryRoute
  '/_workspace/organization': typeof WorkspaceOrganizationRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/oauth/consent': typeof AuthOauthConsentRoute
  '/_public/entries/$entryId': typeof PublicEntriesEntryIdRoute
  '/_workspace/admin/discounts': typeof WorkspaceAdminDiscountsRoute
  '/_workspace/organization/sso': typeof WorkspaceOrganizationSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_workspace/organization/': typeof WorkspaceOrganizationIndexRoute
  '/_public/profiles/organizations/$slug': typeof PublicProfilesOrganizationsSlugRoute
  '/_public/profiles/people/$slug': typeof PublicProfilesPeopleSlugRoute
  '/api/auth/internal/api-key': typeof ApiAuthInternalApiKeyRoute
  '/api/auth/internal/memberships/$organizationId/members/$userId': typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/openapi.json'
    | '/sitemap.xml'
    | '/account-setup'
    | '/sign-in'
    | '/sign-up'
    | '/browse'
    | '/pricing'
    | '/request-discount'
    | '/account'
    | '/discovery'
    | '/organization'
    | '/api/$'
    | '/api/health'
    | '/oauth/consent'
    | '/entries/$entryId'
    | '/admin/discounts'
    | '/organization/sso'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/organization/'
    | '/profiles/organizations/$slug'
    | '/profiles/people/$slug'
    | '/api/auth/internal/api-key'
    | '/api/auth/internal/memberships/$organizationId/members/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/openapi.json'
    | '/sitemap.xml'
    | '/account-setup'
    | '/sign-in'
    | '/sign-up'
    | '/browse'
    | '/pricing'
    | '/request-discount'
    | '/account'
    | '/discovery'
    | '/api/$'
    | '/api/health'
    | '/oauth/consent'
    | '/entries/$entryId'
    | '/admin/discounts'
    | '/organization/sso'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/organization'
    | '/profiles/organizations/$slug'
    | '/profiles/people/$slug'
    | '/api/auth/internal/api-key'
    | '/api/auth/internal/memberships/$organizationId/members/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_workspace'
    | '/dashboard'
    | '/docs'
    | '/openapi.json'
    | '/sitemap.xml'
    | '/_auth/account-setup'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_public/browse'
    | '/_public/pricing'
    | '/_public/request-discount'
    | '/_workspace/account'
    | '/_workspace/discovery'
    | '/_workspace/organization'
    | '/api/$'
    | '/api/health'
    | '/_public/'
    | '/_auth/oauth/consent'
    | '/_public/entries/$entryId'
    | '/_workspace/admin/discounts'
    | '/_workspace/organization/sso'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/_workspace/organization/'
    | '/_public/profiles/organizations/$slug'
    | '/_public/profiles/people/$slug'
    | '/api/auth/internal/api-key'
    | '/api/auth/internal/memberships/$organizationId/members/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiAuthInternalApiKeyRoute: typeof ApiAuthInternalApiKeyRoute
  ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute: typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/organization': {
      id: '/_workspace/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof WorkspaceOrganizationRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/discovery': {
      id: '/_workspace/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof WorkspaceDiscoveryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/account': {
      id: '/_workspace/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WorkspaceAccountRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/request-discount': {
      id: '/_public/request-discount'
      path: '/request-discount'
      fullPath: '/request-discount'
      preLoaderRoute: typeof PublicRequestDiscountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/browse': {
      id: '/_public/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof PublicBrowseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account-setup': {
      id: '/_auth/account-setup'
      path: '/account-setup'
      fullPath: '/account-setup'
      preLoaderRoute: typeof AuthAccountSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_workspace/organization/': {
      id: '/_workspace/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof WorkspaceOrganizationIndexRouteImport
      parentRoute: typeof WorkspaceOrganizationRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/organization/sso': {
      id: '/_workspace/organization/sso'
      path: '/sso'
      fullPath: '/organization/sso'
      preLoaderRoute: typeof WorkspaceOrganizationSsoRouteImport
      parentRoute: typeof WorkspaceOrganizationRoute
    }
    '/_workspace/admin/discounts': {
      id: '/_workspace/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof WorkspaceAdminDiscountsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/entries/$entryId': {
      id: '/_public/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof PublicEntriesEntryIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/oauth/consent': {
      id: '/_auth/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AuthOauthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/internal/api-key': {
      id: '/api/auth/internal/api-key'
      path: '/api/auth/internal/api-key'
      fullPath: '/api/auth/internal/api-key'
      preLoaderRoute: typeof ApiAuthInternalApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/profiles/people/$slug': {
      id: '/_public/profiles/people/$slug'
      path: '/profiles/people/$slug'
      fullPath: '/profiles/people/$slug'
      preLoaderRoute: typeof PublicProfilesPeopleSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/profiles/organizations/$slug': {
      id: '/_public/profiles/organizations/$slug'
      path: '/profiles/organizations/$slug'
      fullPath: '/profiles/organizations/$slug'
      preLoaderRoute: typeof PublicProfilesOrganizationsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/internal/memberships/$organizationId/members/$userId': {
      id: '/api/auth/internal/memberships/$organizationId/members/$userId'
      path: '/api/auth/internal/memberships/$organizationId/members/$userId'
      fullPath: '/api/auth/internal/memberships/$organizationId/members/$userId'
      preLoaderRoute: typeof ApiAuthInternalMembershipsOrganizationIdMembersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthAccountSetupRoute: typeof AuthAccountSetupRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthOauthConsentRoute: typeof AuthOauthConsentRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountSetupRoute: AuthAccountSetupRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthOauthConsentRoute: AuthOauthConsentRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicBrowseRoute: typeof PublicBrowseRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicRequestDiscountRoute: typeof PublicRequestDiscountRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEntriesEntryIdRoute: typeof PublicEntriesEntryIdRoute
  PublicProfilesOrganizationsSlugRoute: typeof PublicProfilesOrganizationsSlugRoute
  PublicProfilesPeopleSlugRoute: typeof PublicProfilesPeopleSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBrowseRoute: PublicBrowseRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicRequestDiscountRoute: PublicRequestDiscountRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicEntriesEntryIdRoute: PublicEntriesEntryIdRoute,
  PublicProfilesOrganizationsSlugRoute: PublicProfilesOrganizationsSlugRoute,
  PublicProfilesPeopleSlugRoute: PublicProfilesPeopleSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface WorkspaceOrganizationRouteChildren {
  WorkspaceOrganizationSsoRoute: typeof WorkspaceOrganizationSsoRoute
  WorkspaceOrganizationIndexRoute: typeof WorkspaceOrganizationIndexRoute
}

const WorkspaceOrganizationRouteChildren: WorkspaceOrganizationRouteChildren = {
  WorkspaceOrganizationSsoRoute: WorkspaceOrganizationSsoRoute,
  WorkspaceOrganizationIndexRoute: WorkspaceOrganizationIndexRoute,
}

const WorkspaceOrganizationRouteWithChildren =
  WorkspaceOrganizationRoute._addFileChildren(
    WorkspaceOrganizationRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceAccountRoute: typeof WorkspaceAccountRoute
  WorkspaceDiscoveryRoute: typeof WorkspaceDiscoveryRoute
  WorkspaceOrganizationRoute: typeof WorkspaceOrganizationRouteWithChildren
  WorkspaceAdminDiscountsRoute: typeof WorkspaceAdminDiscountsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAccountRoute: WorkspaceAccountRoute,
  WorkspaceDiscoveryRoute: WorkspaceDiscoveryRoute,
  WorkspaceOrganizationRoute: WorkspaceOrganizationRouteWithChildren,
  WorkspaceAdminDiscountsRoute: WorkspaceAdminDiscountsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiAuthInternalApiKeyRoute: ApiAuthInternalApiKeyRoute,
  ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute:
    ApiAuthInternalMembershipsOrganizationIdMembersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
