/**
 * Server-side Stripe catalog IDs generated by billing bootstrap.
 *
 * The runtime contract is intentionally small: Stripe credentials plus one
 * generated catalog value. Product, price, and coupon IDs are implementation
 * details owned by bootstrap, not keys an operator has to manage by hand.
 */

export const STRIPE_ATLAS_CATALOG_ENV_KEY = "STRIPE_ATLAS_CATALOG";

export interface StripeAtlasCatalog {
  coupons: StripeAtlasCatalogCoupons;
  prices: StripeAtlasCatalogPrices;
  products: StripeAtlasCatalogProducts;
}

export interface StripeAtlasCatalogCoupons {
  civic_tech_worker: string;
  grassroots_nonprofit: string;
  independent_journalist: string;
  student: string;
}

export interface StripeAtlasCatalogPrices {
  "pro-monthly": string;
  "pro-student-four-month": string;
  "pro-yearly": string;
  "research-pass-once": string;
  "research-pass-weekly": string;
  "team-base-monthly": string;
  "team-base-yearly": string;
  "team-seat-monthly": string;
  "team-seat-yearly": string;
}

export interface StripeAtlasCatalogProducts {
  pro: string;
  "research-pass": string;
  "team-base": string;
  "team-seat": string;
}

export interface AtlasBillingProducts {
  atlas_pro: AtlasProBillingProduct;
  atlas_research_pass: AtlasResearchPassBillingProduct;
  atlas_team: AtlasTeamBillingProduct;
}

export interface AtlasProBillingProduct {
  monthlyPriceId: string;
  studentFourMonthPriceId: string;
  yearlyPriceId: string;
}

export interface AtlasResearchPassBillingProduct {
  oncePriceId: string;
  weeklyPriceId: string;
}

export interface AtlasTeamBillingProduct {
  monthlyPriceId: string;
  monthlySeatPriceId: string;
  yearlyPriceId: string;
  yearlySeatPriceId: string;
}

export interface AtlasDiscountCouponIds {
  civic_tech_worker: string;
  grassroots_nonprofit: string;
  independent_journalist: string;
  student: string;
}

type StripeAtlasCatalogSection = "coupons" | "prices" | "products";

export function getAtlasBillingProducts(): AtlasBillingProducts {
  const catalog = getStripeAtlasCatalog();
  return {
    atlas_pro: {
      monthlyPriceId: catalog.prices["pro-monthly"],
      studentFourMonthPriceId: catalog.prices["pro-student-four-month"],
      yearlyPriceId: catalog.prices["pro-yearly"],
    },
    atlas_research_pass: {
      oncePriceId: catalog.prices["research-pass-once"],
      weeklyPriceId: catalog.prices["research-pass-weekly"],
    },
    atlas_team: {
      monthlyPriceId: catalog.prices["team-base-monthly"],
      monthlySeatPriceId: catalog.prices["team-seat-monthly"],
      yearlyPriceId: catalog.prices["team-base-yearly"],
      yearlySeatPriceId: catalog.prices["team-seat-yearly"],
    },
  };
}

export function getAtlasDiscountCouponIds(): AtlasDiscountCouponIds {
  return getStripeAtlasCatalog().coupons;
}

export function getStripeAtlasCatalog(): StripeAtlasCatalog {
  const rawValue = process.env[STRIPE_ATLAS_CATALOG_ENV_KEY]?.trim();
  if (!rawValue) {
    throw new Error(`${STRIPE_ATLAS_CATALOG_ENV_KEY} is required for billing operations.`);
  }
  return parseStripeAtlasCatalog(rawValue);
}

export function parseStripeAtlasCatalog(rawValue: string): StripeAtlasCatalog {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawValue);
  } catch {
    throw new Error(`${STRIPE_ATLAS_CATALOG_ENV_KEY} must be valid JSON.`);
  }

  if (!isRecord(parsed)) {
    throw new Error(`${STRIPE_ATLAS_CATALOG_ENV_KEY} must be a JSON object.`);
  }

  const products = parseProducts(readSection(parsed, "products"));
  const prices = parsePrices(readSection(parsed, "prices"));
  const coupons = parseCoupons(readSection(parsed, "coupons"));
  return { coupons, prices, products };
}

function parseProducts(section: Record<string, unknown>): StripeAtlasCatalogProducts {
  return {
    pro: readRequiredString(section, "products.pro"),
    "research-pass": readRequiredString(section, "products.research-pass"),
    "team-base": readRequiredString(section, "products.team-base"),
    "team-seat": readRequiredString(section, "products.team-seat"),
  };
}

function parsePrices(section: Record<string, unknown>): StripeAtlasCatalogPrices {
  return {
    "pro-monthly": readRequiredString(section, "prices.pro-monthly"),
    "pro-student-four-month": readRequiredString(section, "prices.pro-student-four-month"),
    "pro-yearly": readRequiredString(section, "prices.pro-yearly"),
    "research-pass-once": readRequiredString(section, "prices.research-pass-once"),
    "research-pass-weekly": readRequiredString(section, "prices.research-pass-weekly"),
    "team-base-monthly": readRequiredString(section, "prices.team-base-monthly"),
    "team-base-yearly": readRequiredString(section, "prices.team-base-yearly"),
    "team-seat-monthly": readRequiredString(section, "prices.team-seat-monthly"),
    "team-seat-yearly": readRequiredString(section, "prices.team-seat-yearly"),
  };
}

function parseCoupons(section: Record<string, unknown>): StripeAtlasCatalogCoupons {
  return {
    civic_tech_worker: readRequiredString(section, "coupons.civic_tech_worker"),
    grassroots_nonprofit: readRequiredString(section, "coupons.grassroots_nonprofit"),
    independent_journalist: readRequiredString(section, "coupons.independent_journalist"),
    student: readRequiredString(section, "coupons.student"),
  };
}

function readSection(
  value: Record<string, unknown>,
  section: StripeAtlasCatalogSection,
): Record<string, unknown> {
  const sectionValue = value[section];
  if (!isRecord(sectionValue)) {
    throw new Error(
      `${STRIPE_ATLAS_CATALOG_ENV_KEY}.${section} is required for billing operations.`,
    );
  }
  return sectionValue;
}

function readRequiredString(value: Record<string, unknown>, path: string): string {
  const item = value[path.slice(path.lastIndexOf(".") + 1)];
  if (typeof item !== "string" || !item.trim()) {
    throw new Error(`${STRIPE_ATLAS_CATALOG_ENV_KEY}.${path} is required for billing operations.`);
  }
  return item.trim();
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
