"""Org-scoped coverage target endpoints."""

from __future__ import annotations

import csv

from atlas.domains.discovery.coverage_targets import CoverageTargetCRUD

from .api_org_coverage_imports import (
    ParsedCoverageTargetImportRow,
    _coverage_import_error_detail,
    _normalize_import_header,
    _normalized_import_row,
    _parse_coverage_target_import_csv,
    _parse_import_gaps,
    _parse_import_review_state,
    _parse_import_row,
    _split_import_cell,
    _validate_import_headers,
    _validate_import_target_links,
)
from .api_org_coverage_models import (
    COVERAGE_IMPORT_COLUMNS,
    COVERAGE_IMPORT_OPTIONAL_COLUMNS,
    COVERAGE_IMPORT_REQUIRED_COLUMNS,
    COVERAGE_REPORT_CSV_COLUMNS,
    COVERAGE_REVIEW_STATES,
    CoverageReportResponse,
    CoverageReportSummary,
    CoverageReportTarget,
    CoverageTargetCollectionResponse,
    CoverageTargetCreateRequest,
    CoverageTargetDetailDiscoveryRun,
    CoverageTargetDetailEntry,
    CoverageTargetDetailResponse,
    CoverageTargetDetailSource,
    CoverageTargetGap,
    CoverageTargetImportError,
    CoverageTargetImportRequest,
    CoverageTargetImportResponse,
    CoverageTargetResponse,
    CoverageTargetUpdateRequest,
)
from .api_org_coverage_report import (
    _coverage_report_csv,
    _detail_entry,
    _detail_source,
    _report_target,
    _status_explanation,
    _target_detail_response,
    build_coverage_report_response,
)
from .api_org_coverage_routes import (
    _target_update_input,
    _validate_target_fields,
    _validate_target_links,
    _verify_org_access,
    create_org_coverage_target,
    export_org_coverage_targets,
    get_db,
    get_org_coverage_target,
    import_org_coverage_targets,
    list_org_coverage_targets,
    router,
    update_org_coverage_target,
)

__all__ = [
    "COVERAGE_IMPORT_COLUMNS",
    "COVERAGE_IMPORT_OPTIONAL_COLUMNS",
    "COVERAGE_IMPORT_REQUIRED_COLUMNS",
    "COVERAGE_REPORT_CSV_COLUMNS",
    "COVERAGE_REVIEW_STATES",
    "CoverageReportResponse",
    "CoverageReportSummary",
    "CoverageReportTarget",
    "CoverageTargetCRUD",
    "CoverageTargetCollectionResponse",
    "CoverageTargetCreateRequest",
    "CoverageTargetDetailDiscoveryRun",
    "CoverageTargetDetailEntry",
    "CoverageTargetDetailResponse",
    "CoverageTargetDetailSource",
    "CoverageTargetGap",
    "CoverageTargetImportError",
    "CoverageTargetImportRequest",
    "CoverageTargetImportResponse",
    "CoverageTargetResponse",
    "CoverageTargetUpdateRequest",
    "ParsedCoverageTargetImportRow",
    "_coverage_import_error_detail",
    "_coverage_report_csv",
    "_detail_entry",
    "_detail_source",
    "_normalize_import_header",
    "_normalized_import_row",
    "_parse_coverage_target_import_csv",
    "_parse_import_gaps",
    "_parse_import_review_state",
    "_parse_import_row",
    "_report_target",
    "_split_import_cell",
    "_status_explanation",
    "_target_detail_response",
    "_target_update_input",
    "_validate_import_headers",
    "_validate_import_target_links",
    "_validate_target_fields",
    "_validate_target_links",
    "_verify_org_access",
    "build_coverage_report_response",
    "create_org_coverage_target",
    "csv",
    "export_org_coverage_targets",
    "get_db",
    "get_org_coverage_target",
    "import_org_coverage_targets",
    "list_org_coverage_targets",
    "router",
    "update_org_coverage_target",
]
