"""
Search term mappings for the autodiscovery pipeline.

Maps each issue area slug to natural language search terms used in
query generation for web searches.
"""

__all__ = ["ISSUE_SEARCH_TERMS"]

ISSUE_SEARCH_TERMS: dict[str, list[str]] = {
    # Economic Security
    "automation_and_ai_displacement": [
        "automation",
        "AI displacement",
        "job automation",
        "artificial intelligence jobs",
        "worker displacement",
        "technological unemployment",
    ],
    "gig_economy_and_precarious_work": [
        "gig economy",
        "gig workers",
        "contract workers",
        "precarious work",
        "temporary workers",
        "freelance workers",
    ],
    "income_inequality_and_wealth_concentration": [
        "income inequality",
        "wealth gap",
        "wealth concentration",
        "wage gap",
        "economic inequality",
        "inequality",
    ],
    "healthcare_economics_and_medical_debt": [
        "medical debt",
        "healthcare costs",
        "health insurance",
        "healthcare affordability",
        "healthcare access",
        "medical bankruptcy",
    ],
    "student_debt_and_college_affordability": [
        "student debt",
        "student loans",
        "college affordability",
        "higher education costs",
        "student loan forgiveness",
        "education affordability",
    ],
    # Housing and the Built Environment
    "housing_affordability": [
        "affordable housing",
        "housing crisis",
        "rent",
        "housing affordability",
        "community land trust",
        "tenant organizing",
        "rental housing",
    ],
    "suburban_sprawl_and_car_dependency": [
        "suburban sprawl",
        "car dependency",
        "urban sprawl",
        "land use",
        "car culture",
        "sprawl",
    ],
    "homelessness_and_housing_insecurity": [
        "homelessness",
        "housing insecurity",
        "unhoused",
        "housing instability",
        "homeless services",
    ],
    "zoning_and_land_use": [
        "zoning",
        "land use",
        "zoning reform",
        "zoning policy",
        "urban planning",
        "land use planning",
    ],
    # Climate and Environment
    "climate_adaptation_and_resilience": [
        "climate adaptation",
        "climate resilience",
        "climate change",
        "climate preparedness",
        "climate impacts",
    ],
    "environmental_justice_and_pollution": [
        "environmental justice",
        "pollution",
        "environmental racism",
        "toxic pollution",
        "air quality",
        "environmental health",
    ],
    "sustainable_agriculture_and_food_systems": [
        "sustainable agriculture",
        "local food",
        "food security",
        "food systems",
        "agricultural sustainability",
        "urban farming",
    ],
    "water_access_and_infrastructure": [
        "water access",
        "water quality",
        "water infrastructure",
        "drinking water",
        "water systems",
        "clean water",
    ],
    "energy_transition": [
        "renewable energy",
        "energy transition",
        "clean energy",
        "solar",
        "wind energy",
        "just energy transition",
    ],
    # Democracy and Governance
    "voter_suppression_and_electoral_access": [
        "voter suppression",
        "voting rights",
        "electoral access",
        "voter registration",
        "voting access",
    ],
    "local_government_and_civic_engagement": [
        "local government",
        "civic engagement",
        "community organizing",
        "local politics",
        "community participation",
    ],
    "political_polarization_and_democratic_norms": [
        "political polarization",
        "democratic norms",
        "institutional health",
        "polarization",
        "democratic institutions",
    ],
    "money_in_politics": [
        "campaign finance",
        "money in politics",
        "political donations",
        "lobbying",
        "dark money",
    ],
    "electoral_reform": [
        "electoral reform",
        "voting systems",
        "election administration",
        "election reform",
        "representation",
    ],
    # Technology and Information
    "social_media_and_mental_health": [
        "social media",
        "mental health",
        "digital mental health",
        "social media mental health",
        "tech and mental health",
    ],
    "misinformation_and_epistemic_crisis": [
        "misinformation",
        "disinformation",
        "fake news",
        "information ecosystem",
        "epistemic crisis",
    ],
    "digital_privacy_and_surveillance": [
        "digital privacy",
        "surveillance",
        "privacy rights",
        "data privacy",
        "data protection",
    ],
    "broadband_access_and_digital_divide": [
        "broadband access",
        "digital divide",
        "internet access",
        "broadband",
        "digital equity",
    ],
    "platform_monopolies_and_tech_accountability": [
        "platform monopolies",
        "tech monopolies",
        "big tech",
        "tech accountability",
        "platform regulation",
    ],
    # Education
    "k12_education_inequality": [
        "K-12 education",
        "education inequality",
        "school inequality",
        "education equity",
        "school funding",
    ],
    "higher_education_affordability": [
        "higher education",
        "college affordability",
        "university",
        "college access",
        "college completion",
    ],
    "vocational_and_alternative_pathways": [
        "vocational training",
        "apprenticeships",
        "alternative education",
        "skills training",
        "trade school",
    ],
    "education_funding_and_policy": [
        "education policy",
        "education funding",
        "school policy",
        "education reform",
    ],
    # Health and Social Connection
    "mental_health_crisis_and_access": [
        "mental health",
        "mental illness",
        "mental health services",
        "mental health crisis",
        "depression",
    ],
    "loneliness_and_social_isolation": [
        "loneliness",
        "social isolation",
        "social connection",
        "community",
        "belonging",
    ],
    "addiction_and_harm_reduction": [
        "addiction",
        "substance abuse",
        "harm reduction",
        "opioid",
        "drug treatment",
    ],
    "healthcare_access_and_coverage": [
        "healthcare access",
        "health insurance",
        "healthcare coverage",
        "health equity",
        "uninsured",
    ],
    "community_health_infrastructure": [
        "community health",
        "public health",
        "health clinics",
        "health infrastructure",
        "primary care",
    ],
    # Infrastructure and Public Goods
    "transportation_and_mobility": [
        "transportation",
        "transit",
        "public transportation",
        "bus",
        "bike infrastructure",
        "pedestrian",
    ],
    "public_transit": [
        "public transit",
        "transit system",
        "bus rapid transit",
        "light rail",
        "transit equity",
    ],
    "broadband_and_digital_access": [
        "broadband infrastructure",
        "broadband access",
        "internet infrastructure",
        "fiber optic",
    ],
    "water_infrastructure": [
        "water infrastructure",
        "water systems",
        "pipe",
        "water main",
        "water service",
    ],
    "physical_infrastructure_decay": [
        "infrastructure",
        "infrastructure decay",
        "infrastructure maintenance",
        "roads",
        "bridges",
    ],
    # Justice and Public Safety
    "criminal_justice_reform_and_mass_incarceration": [
        "criminal justice reform",
        "mass incarceration",
        "incarceration",
        "justice reform",
        "sentencing reform",
    ],
    "policing_and_community_safety": [
        "policing",
        "police reform",
        "community safety",
        "public safety",
        "police accountability",
    ],
    "immigration_and_belonging": [
        "immigration",
        "immigrant rights",
        "immigration policy",
        "deportation",
        "immigrant communities",
    ],
    "restorative_justice": [
        "restorative justice",
        "conflict resolution",
        "community justice",
        "healing justice",
    ],
    # Rural-Urban Divide
    "rural_economic_decline_and_brain_drain": [
        "rural economy",
        "rural economic decline",
        "brain drain",
        "rural jobs",
        "rural development",
    ],
    "cultural_resentment_and_political_division": [
        "rural urban divide",
        "cultural resentment",
        "political division",
        "rural urban split",
    ],
    "rural_healthcare_and_services": [
        "rural healthcare",
        "rural health",
        "rural services",
        "rural clinics",
    ],
    "urban_rural_coalition_building": [
        "urban rural coalition",
        "cross community organizing",
        "coalition building",
    ],
    # Labor and Worker Power
    "union_organizing": [
        "union organizing",
        "unionization",
        "labor organizing",
        "collective bargaining",
        "labor movement",
    ],
    "worker_cooperatives": [
        "worker cooperative",
        "worker-owned",
        "co-op",
        "cooperative enterprise",
        "employee ownership",
    ],
    "workplace_safety_and_conditions": [
        "workplace safety",
        "workplace conditions",
        "occupational health",
        "worker safety",
        "OSHA",
    ],
    "wage_theft_and_labor_rights": [
        "wage theft",
        "labor rights",
        "worker rights",
        "wage violations",
        "labor standards",
    ],
    "just_transition": [
        "just transition",
        "energy transition",
        "worker transition",
        "transitional support",
    ],
}
