// This file is auto-generated by TanStack Router
// DO NOT EDIT THIS FILE MANUALLY

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as AtlasImport } from "./routes/atlas";
import { Route as DiscoveryImport } from "./routes/discovery";
import { Route as AtlasEntryIdImport } from "./routes/atlas.$entryId";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AtlasRoute = AtlasImport.update({
  id: "/atlas",
  path: "/atlas",
  getParentRoute: () => rootRoute,
} as any);

const DiscoveryRoute = DiscoveryImport.update({
  id: "/discovery",
  path: "/discovery",
  getParentRoute: () => rootRoute,
} as any);

const AtlasEntryIdRoute = AtlasEntryIdImport.update({
  id: "/atlas/$entryId",
  path: "/atlas/$entryId",
  getParentRoute: () => rootRoute,
} as any);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/atlas": {
      id: "/atlas";
      path: "/atlas";
      fullPath: "/atlas";
      preLoaderRoute: typeof AtlasImport;
      parentRoute: typeof rootRoute;
    };
    "/discovery": {
      id: "/discovery";
      path: "/discovery";
      fullPath: "/discovery";
      preLoaderRoute: typeof DiscoveryImport;
      parentRoute: typeof rootRoute;
    };
    "/atlas/$entryId": {
      id: "/atlas/$entryId";
      path: "/atlas/$entryId";
      fullPath: "/atlas/$entryId";
      preLoaderRoute: typeof AtlasEntryIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/atlas": typeof AtlasRoute;
  "/discovery": typeof DiscoveryRoute;
  "/atlas/$entryId": typeof AtlasEntryIdRoute;
}

export const routeTree = rootRoute._addFileChildren([
  IndexRoute,
  AtlasRoute,
  DiscoveryRoute,
  AtlasEntryIdRoute,
]);

declare module "@tanstack/react-router" {
  interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/atlas": typeof AtlasRoute;
    "/discovery": typeof DiscoveryRoute;
    "/atlas/$entryId": typeof AtlasEntryIdRoute;
  }
}
